### ISSUE TITLE
HTTP feeds fetched as HTTPS

### ISSUE THREAD

**Issue by cellscape** [skeeto/elfeed#10]
Problem happens when elfeed fetches simultaneously HTTPS and HTTP feed. Emacs just stucks for a while and update doesn't proceed.

Here is part of backtrace:

    Debugger entered--Lisp error: (quit)
      re-search-forward("\\(^    Verify return code: .+\n---\n\\|^- Simple Client Mode:\n\\(\n\\|^\\*\\*\\* Starting TLS handshake\n\\)*\\)" nil t)
      open-tls-stream("feeds2.feedburner.com" #<buffer  *url-http-temp*-69304> "feeds2.feedburner.com" 80)
      network-stream-open-tls("feeds2.feedburner.com" #<buffer  *url-http-temp*-69304> "feeds2.feedburner.com" 80 (:type tls :nowait t))
      open-network-stream("feeds2.feedburner.com" #<buffer  *url-http-temp*-69304> "feeds2.feedburner.com" 80 :type tls :nowait t)
      ... 
      url-retrieve
      ... 
      elfeed--check-queue()
      ... 
      url-http-activate-callback()
      ...
      url-http
      url-https
      ...
      elfeed--check-queue()

Looking at backtrace, I can see that url-open-stream tries to use tls method for port 80 which is cleary invalid and results in my issue. Normally url-open-stream checks for url-gateway-method variable. However this variable is set by url-https down the stack and elfeed--check-queue asks to retreive new HTTP URL with url-gateway-method already set to tls.

One solution I could propose is to reset url-gateway-method to default value but I don't like this approach. Perhaps code that manages queue can be changed in some other way to fix the issue? 

BTW what do you think about using url-queue-retrieve?

**Comment by skeeto** [comment]
I switched it over to `url-queue-retrieve` just now. No more custom queue framework. The only downside as far as I can tell is that it breaks differently in Windows than my original queue framework.

What prompted this is that YouTube just dropped their v2 API and the new v3 API is a whole lot more sensitive about rate-limiting, so Elfeed needs to be more careful about reusing connections to avoid trouble.

I'm going to close this since, if this bug is still around, it's formally an Emacs (url-queue) bug now.
