### ISSUE TITLE
Add Twitter as source of feed?

### ISSUE THREAD

**Issue by ReneFroger** [skeeto/elfeed#105]
Would it possible to add feed from my twitter account in elfeed (like Twittering mode does)?

It would be nice to have one package that gives you the RSS feed and tweets, like some apps on smartphones does.

**Comment by skeeto** [comment]
Twitter used to host RSS feeds of content up until June 2013, when they
locked down their API. That's too bad because it would have instantly
solved this problem.

Something like this could be achieved as an extension to Elfeed.
Currently, other packages can easily "inject" new entries into Elfeed's
database (elfeed-db-add), which will behave the same way as any normal
RSS and Atom entries. If someone was serious about doing this (or
something like it), I'd probably formalize the API a bit more. For
example, Twitter data could come in from twittering-mode, which already
did all the Twitter API heavy lifting.

I don't use Twitter, so it's not something I ever plan to do myself, but
I would certainly collaborate enough to ensure Elfeed is friendly to
such extensions.

**Comment by ReneFroger** [comment]
Clear enough. Too bad that Twitter is not collaboraitng enough for such additions. I will improve my Elisp knowledge first before I could consider to contribute to such a big task. 

Thanks for this package!

**Comment by daraul** [comment]
@ReneFroger, have you revisited this? I thought it would be an ideal workflow for emacs+elfeed.
