### ISSUE TITLE
File index is large (9.9M), really open? a.k.a Tips about db maintenance.

### ISSUE THREAD

**Issue by kmicu** [skeeto/elfeed#11]
I have currently ~ 550 feeds. (a lot of youtube and vimeo feeds)
Elfeed's db is ~ 526 MiB.

Can you give me some tips about db maintenance?
- How can I physically remove entries older than X weeks?
- How can I keep only favorite entries?
- Maybe we can split elfeed db in two parts - operations and archive?

Any feedback is appreciated before I run out of disk space :)

**Comment by alphapapa** [comment]
@skeeto Sorry if I missed it, but I can't find anything with a quick googling around.  How did that Emacs patch turn out?  Did it get rejected?  Seems like adding support for SQLite to Emacs directly would be ideal.

**Comment by skeeto** [comment]
I didn't go anywhere with that patch. I got stuck on how to represent 
opaque SQLite handles in a garbage collection friendly way (process 
handles?). The right approach these days is to implement SQLite bindings 
as a module (Emacs 25) rather than a patch, which a few people have 
already done. Module "user pointers" are just about perfect for 
representing SQLite handles, and it's the thing I needed when writing my 
patch.

That being said, I've basically given up on the idea of using SQLite for 
Elfeed. Too many obstacles, and I value simple portability. The custom 
database is Good Enough right now, and I've since made significant 
efforts to improve Elfeed's elisp performance:

* http://nullprogram.com/blog/2016/12/11/
* http://nullprogram.com/blog/2016/12/27/

This allows Elfeed databases to scale further, and the march of 
technological progress bringing us faster and faster computers will 
gradually allows for larger and larger databases in the future. Emacs 
own elisp performance occasionally improves, too, with compiler, 
language, and VM enhancements.

**Comment by alphapapa** [comment]
Cool, thanks for explaining, I'll check out those links.

The only concern I have is about robustness.  I know SQLite is very good about recovery from crashes, power loss, etc.  Emacs handles this well for regular files that are open in buffers by saving them to temp files regularly and offering to recover them.  Does Elfeed handle this as well, or is there risk of db corruption in these cases?  I know it's not an easy problem to solve from scratch.

**Comment by skeeto** [comment]
The database is written out the same way Emacs normally writes out 
regular files. As long as write-region-inhibit-fsync is nil (the 
default), it will do something like:

1) write the database index to a temp file
2) fsync
3) rename the temp file over the target file
4) fsync

This means it's not possible to observe a partially-written database 
index even if there was a power failure in the middle of saving. It's 
actually really easy in this case because the entire index is written in 
full each time it's saved. It's a lot more difficult if a file is 
updated in place, especially if under contention with other threads and 
processes (e.g. the problem that SQLite solves). The loose "content" 
files are written with fsync disabled since this data is unimportant, 
and disabling fsync has dramatic performance improvements for that part 
of the database.

**Comment by alphapapa** [comment]
Thanks.
