### ISSUE TITLE
XML parsing

### ISSUE THREAD

**Issue by foudfou** [skeeto/elfeed#112]
This feed http://www.heise.de/open/news/news-atom.xml renders void entries in elfeed, although `content` is defined.

**Comment by skeeto** [comment]
I'm surprised this issue hasn't come up yet, since this bug has probably
been around since the beginning. The issue is that this feed uses
embedded XHTML (allowed by Atom). This gets parsed with the rest of the
feed document by the XML parser. When Elfeed builds the entry, it needs
to convert the data structure back into XML so that it can be reparsed
later by shr in elfeed-show.
