### ISSUE TITLE
error on feed update: error XML: (Not Well-Formed) 

### ISSUE THREAD

**Issue by zeltak** [skeeto/elfeed#119]
Hi i have been using elfeed for the past week and really loving it
i do think i am not getting all the feeds updated, and i do notice errors during update such as:

```
Elfeed parse failed for http://omnifeed.com/feed/www.engadget.com/rss-full.xml: (error XML: (Well-Formed) Invalid character)
Elfeed fetch failed for http://amarok.kde.org/blog/feeds/index.rss2: (:error (error http 404) :redirect "https://amarok.kde.org/blog/feeds/index.rss2")
Elfeed fetch failed for http://ampache.org/blog/index.php?/feeds/index.rss2: (:error (error http 404))
Elfeed parse failed for http://ubuntuweblogs.org/atom.xml: (error XML: (Not Well-Formed) Invalid end tag `noscript' (expecting `meta'))
```

here is link to my full elfeed config:
https://paste.xinu.at/0Khjf/org

thx so much 

best

Z

**Comment by skeeto** [comment]
You're getting errors because none of these are RSS or Atom feeds.

OmniFeed looks like it's a feed reader itself and doesn't actually host
an RSS feed. You probably want to subscribe to the original feed
instead:

  http://www.engadget.com/rss.xml

The Amarok feed URL is dead and looks like it was moved here:

  https://amarok.kde.org/en/rss.xml

The last one, ubuntuwebblogs, is just a parked domain, so there's
nothing there. It's serving up HTML with ads instead of a feed.

**Comment by skeeto** [comment]
Closing since this is old and not an Elfeed issue.
