### ISSUE TITLE
Text from feeds can set the mode (and give errors)

### ISSUE THREAD

**Issue by jannisteunissen** [skeeto/elfeed#161]
One of my feeds contains the text "Easy way to add -*- mode: org; -*- to my notes files?"

This gives an error message upon starting elfeed, because set-auto-mode() is called after loading the database, which tries to activate org-mode, leading to a 'stack overflow in regexp' error.

[elfeed_bug.txt](https://github.com/skeeto/elfeed/files/263574/elfeed_bug.txt)

**Comment by skeeto** [comment]
Very interesting bug! I hadn't expected this behavior from Emacs, though it makes sense. I imagine the scan for local variables was slowing down Elfeed's startup, too. I believe 40d892c fixes it.

Fortunately this isn't a security issue since Emacs is (rightfully) very conservative about local variables in files. I'm considering opening the index file differently to prevent any other sort of Emacs magic from happening.

**Comment by jannisteunissen** [comment]
It's working working fine with the new version, thanks!
