### ISSUE TITLE
elfeed fails on planet python feed

### ISSUE THREAD

**Issue by slackorama** [skeeto/elfeed#165]
Getting these two errors when elfeed tries to download the feed from planet python

    [2016-05-26 09:48:26] [error]: Elfeed fetch failed for http://planetpython.org/rss20.xml: (:error (error connection-failed "failed with code 111\n" :host "planetpython.org" :service 80))
    [2016-05-26 09:48:26] [error]: Elfeed fetch failed for http://planetpython.org/rss20.xml: (:error (error connection-failed "deleted\n" :host "planetpython.org" :service 80) :error (error connection-failed "failed with code 111\n" :host "planetpython.org" :service 80))

A curl from the same box shows a success:

    ; curl -D- -o /dev/null -s 'http://planetpython.org/rss20.xml?foo=bar'  
    HTTP/1.1 200 OK
    Server: nginx
    Date: Thu, 26 May 2016 16:47:15 GMT
    Content-Type: text/xml
    Content-Length: 239262
    Last-Modified: Thu, 26 May 2016 13:49:53 GMT
    Connection: keep-alive
    ETag: "5746ff01-3a69e"
    Accept-Ranges: bytes

Using elfeed 1.40 on emacs 24.4.1 on Ubuntu 14.04

**Comment by skeeto** [comment]
I suspect this is a local network issue on your end despite the fact
that curl is working fine with this URL. I'm unable to reproduce the
issue for myself. What happens when you fetch the feed directly via
url-retrieve?

    (pop-to-buffer
     (url-retrieve-synchronously "http://planetpython.org/rss20.xml"))

Does this pop up a buffer with the expected RSS content?

And, by the way, thanks for including all your version information up
front. That helps to immediately narrow things down.

**Comment by slackorama** [comment]
Yeah, url-retrieve shows an empty buffer with failed in the title. Weirdness abounds.

Sorry to trouble you. I was hoping it was something you had seen before. I have about 40 feeds going and this is the only one that has this problem. I'll dig into it a bit more on my side.

Thanks for elfeed! I use it daily.
