### ISSUE TITLE
Issue when updating feed

### ISSUE THREAD

**Issue by litanlitudan** [skeeto/elfeed#167]
Hi
Got this error 
Error running timer `elfeed-curl--run-queue': (wrong-type-argument char-or-string-p softwares)
when trying to update the feed.

Thanks in advance.

**Comment by skeeto** [comment]
When you eval (elfeed-feed-list) is it strictly a list of strings?

    (cl-every #'stringp (elfeed-feed-list))

From your error message it looks like the symbol "softwares" somehow got
into the curl request. I'd like to know how.

Since this kind of error completely disrupts the queue, Elfeed will need
to manually check the user-provided values going in before they disrupt
an async operation.

**Comment by litanlitudan** [comment]
Turns out, I forgot to add parenthesis around softwares.

Thanks
