### ISSUE TITLE
Getting Gmail feed to work

### ISSUE THREAD

**Issue by tsweeney256** [skeeto/elfeed#175]
OS: Ubuntu 16.04
Emacs: 24.5.1
Elfeed: 2.0.0 (using cURL 7.47.0)

I'm new to both Emacs and Elfeed and have been trying to switch from RSSOwl to Elfeed, and I've gotten all of my feeds to work very easily aside from my Gmail feeds.

First issue I ran into was having Elfeed give Google my username and password.
I got around this by overriding `elfeed-curl--args` and adding `(push "--netrc" args)` to tell cURL to check my netrc file to make Google happy. This part worked but I don't know if there's a better way to do this.

However, after solving the authentication issue, I started getting the following error in my elfeed-log buffer
`[2016-09-11 14:24:40] [error]: https://mail.google.com/mail/u/0/feed/atom: (wrong-type-argument number-or-marker-p nil)`
Investigating it I realized Gmail's feed was using Atom 0.3, which I don't think Elfeed supports, judging by the `elfeed-entries-from-atom` function. 
I thought I might be able to get it to work by adding in `(xml-query '(modified *) entry)` for where it checks for the date, but I still get the same error. Unfortunately I haven't been able to figure out precisely what is causing that error, so I haven't been able to go any farther.

Is there any plans on supporting Atom 0.3 and is there any way I can get my Gmail feeds to work for the time being?

example feed:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<title>Gmail - Inbox for tsweeney256@gmail.com</title>
	<tagline>New messages in your Gmail Inbox</tagline>
	<fullcount>1</fullcount>
	<link rel="alternate" href="https://mail.google.com/mail/u/0" type="text/html" />
	<modified>2016-09-11T15:36:51Z</modified>
	<entry>
		<title>test</title>
		<summary>test</summary>
		<link rel="alternate" href="https://mail.google.com/mail/u/0?account_id=tsweeney256@gmail.com&amp;message_id=157156af1e897dee&amp;view=conv&amp;extsrc=atom" type="text/html" />
		<modified>2016-09-10T18:45:12Z</modified>
		<issued>2016-09-10T18:45:12Z</issued>
		<id>tag:gmail.google.com,2004:1545111457296383470</id>
		<author>
			<name>Thomas Sweeney</name>
			<email>foo@bar.com</email>
		</author>
	</entry>
</feed>
```

**Comment by skeeto** [comment]
Thank you for your very thorough report! You included all the
information I needed to sort this out. And that's some very impressive
debugging for someone new to Emacs. I'm seriously impressed.

You'll notice there are three separate fixes here.

1) Atom is much stricter than RSS (it's one reason I like it better),
   and Elfeed pretty much assumes that all Atom feeds are valid, since
   that's almost always the case. As you noticed, the date tags are
   different for these Atom 0.3 feeds, making them invalid Atom 1.0
   feeds. This leads to nil dates, which breaks the filter, among other
   things. The first fix ensures a valid date is always entered. The nil
   dates are database corruption in a sense, and the easiest course of
   action is to discard your database index file if you're getting type
   errors. If it's important to you, I can help you recover your index.
   The dates just need to be turned into numerical values.

2) I added some minimal support for Atom 0.3 exactly the way you were
   speculating: using those older date tags as fallbacks. This allows at
   least this feed to work. I don't really care about Atom 0.3, so I'm
   fine with ad hoc support like this.

3) I added an elfeed-curl-extra-arguments customization. You can put
   your "--netrc" argument in there. I briefly considered allowing this
   variable to alternatively be assigned to a function. This function
   would accept a URL and return the extra arguments for that particular
   URL. This would probably be the route to take if you were doing OAuth
   2.0, since you don't want to send that out to everyone. I decided to
   leave that feature out since it complicates connection re-use (URLs
   fetched on the same connection must use the same cURL arguments,
   since they share an invocation).

Does that fix everything?

**Comment by tsweeney256** [comment]
Yes that works beautifully. Thank you very much :)
