### ISSUE TITLE
Download full content of articles

### ISSUE THREAD

**Issue by csantosb** [skeeto/elfeed#177]
Sometimes it happens to have feeds that display only a summary, in
this case, it would be very useful to fetch the original article
automatically, similarly to the way miniflux does.

Is it possible to achieve this today with elfeed ?

**Comment by skeeto** [comment]
It's not a feature I'm interested in adding to Elfeed, but I think it
could be done easily as an extension. For example, the simplest approach
is to set your browser to eww, or another Emacs browser, and view
entries (i.e. "b") through this browser.

Since you mentioned "automatic" and presumably want to pre-fetch these,
another approach is to fire off a download ("wget -m"?) for the entry
link in an elfeed-new-entry-hook. Then make an elfeed-search command to
bring up the downloaded content however you'd prefer.

**Comment by csantosb** [comment]
Ok, thanks. Of course, browsing with eww is a possibility. However, I
am interested on reading my feeds offline. While online, and during
the donwload, I should detect incomplete feeds and download the full
article. I'll see how to implement this.

**Comment by csantosb** [comment]
This blog [post](https://punchagan.muse-amuse.in/posts/elfeed-hook-to-fetch-full-content.html) fixes the issue for me. Closing.

**Comment by csantosb** [comment]
For the sake of completeness, I have to mention this address too

      http://fivefilters.org/content-only/

which offers self hosted features.
