### ISSUE TITLE
elfeed-add-feed, x-get-selection-value, and more

### ISSUE THREAD

**Issue by holomorph** [skeeto/elfeed#181]
hi!

`x-get-selection-value` signals an error, complaining "No selection is available" here.  This is unfortunate because it then prevents falling through to the kill ring (which is where my feed is!) Perhaps you have a particular reason for using this, but for a similar functionality in transmission.el I used `x-get-selection`, which just returns nil if no selection data is found.

Oh, also, supposedly using the `INITIAL-CONTENTS` argument of read-from-minibuffer is deprecated.  I vaguely remember reading about that recently; IIRC the elisp manual has an explanation: ah yes, from the `read-from-minibuffer` index item, you get linked to `(info "(elisp) Initial Input")`

I also did it slightly differently (with a hook) and now I'm thinking it might be slightly more useful to instead accumulate the results from each thing-that-might-give-you-a-string, and put them in the `DEFAULT-VALUE` argument of `read-from-minibuffer`, so one can M-n through the different possible sources.

**Comment by holomorph** [comment]
oh, you might also consider adding some things to look at point; e.g. `url-get-url-at-point`, `eww-links-at-point`, `(get-text-property (point) 'shr-url)`, etc.

sorry for putting half a dozen topics into the issue :)

**Comment by skeeto** [comment]
I can't think of any reason why I used `x-get-selection-value` over `x-get-selection`. I probably just saw it first. Someday when I drop support for Emacs 24, this will be replaced with the Emacs 25 unified clipboard functions.

As for `INITIAL-CONTENTS`, the manual says it's "*mostly* deprecated." :-) I don't normally use it, but I like how it works in this particular case. I also like your idea for collecting the various options and presenting them all. Since I never actually use `elfeed-add-feed` myself outside of testing, implementing this isn't a priority for me, but I'd accept a well-done PR for it.
