### ISSUE TITLE
Inherit/grab author and tag info from feed

### ISSUE THREAD

**Issue by emacsomancer** [skeeto/elfeed#183]
Some blogs, e.g. https://boingboing.net/2016/11/23/new-role-playing-game-has-clev.html , have posts pre-tagged with author and label/tag information. Is there a way to inherit this in elfeed? And to be able to sort/perform actions based on tags/author? (E.g. ignore posts by certain authors, tag post based on author, &c.)

**Comment by skeeto** [comment]
Until now, this information wasn't retrieved from the XML. RSS has an
author element, though it's not often used. Atom requires either the
feed as a whole or each entry to have an author element. What
complicates matters is the example you provided is neither of these. It
extends RSS with Dublin Core (dc) and uses its creator element.

I just pushed a7c3d5e, which adds an :author metadata item
(elfeed-meta). I didn't reserve a slot in the struct for the author, so
it's going into the "meta" catch-all. You can query this property when
setting your own tags.

I also just pushed 357eebe which gathers up categories and puts them in
the :categories metadata. Unlike tags, these are in string form since
they're not necessarily symbol-like.

**Comment by emacsomancer** [comment]
Cheers!  I'll have to dig into the docs to try to figure out how to best use :author (as "meta") and categories.
