### ISSUE TITLE
Error: couldn't parse tag?

### ISSUE THREAD

**Issue by pqnelson** [skeeto/elfeed#187]
Hello,

I got an error from elfeed while trying to handle one wordpress feed:

```
[error]: http://legislativegazette.com/archives/category/politics/feed: (error XML: (Well-Formed) Couldn’t parse tag: i<c.length;)
```

The XML for the feed seems to be alright, but I'm more curious as to what caused the problem (and would be delighted if there's an easy fix).

I'm using GNU Emacs 26.0.50.2, if it's at all relevant.

**Comment by skeeto** [comment]
Looks like they've got some sort of anti-bot mechanism in place. On the
first request it serves an HTML document with JavaScript rather than a
feed. That's the XML parsing error you're seeing. If you manually grab
the page with curl or wget you'll see this. The JavaScript implements a
challenge so that only user agents that can execute JavaScript (i.e.
browsers) can continue to the content.

However, it's either not sophisticated or it's broken because an
immediate followup request, even for a different object, results in the
correct content rather than a challenge, regardless if challenge was
ever executed. You can see this in Elfeed where every other update works
correctly. I wasn't able to determine if there's a time limit for the
second request, but it's at least longer than a minute.

Also while I was poking at this, the server blocked me several times
forcing me to perform CAPTCHA challenge before I was unblocked. That
would also be a problem if you trigger that block from Elfeed.

So your options are the following (#3 being what I would do):

1) Put up with their misbehaving server and allow every other request to
   fail. You may have to occasionally visit with a browser and solve a
   CAPTCHA.

2) Come up with some mechanism to "prime" the challenge request before
   Elfeed runs. Simply visiting with a browser isn't enough since it
   will execute the challenge and then consume the desired response. A
   single curl/wget request should do it.

3) Ask them to disable anti-bot protection on their feed. For web pages
   intended to be consumed by humans sitting at web browsers, an
   anti-bot challenge not entirely unreasonable (though I still think
   it's crummy), but syndication feeds are very much intended to be
   consumed by non-browser user agents, including bots, so they
   shouldn't require a browser to access a feed.

**Comment by pqnelson** [comment]
@skeeto - Thanks for your very informative (and very prompt) response!

I tend to agree with your assessment, and will ask them to kindly disable their bot-protection on the RSS feeds.

(So --- I will close this issue.)
