### ISSUE TITLE
Provide xml-query.el as a separate package

### ISSUE THREAD

**Issue by marsam** [skeeto/elfeed#189]
Hi:
Thanks for your work in elfeed. Would you mind releasing `xml-query.el` as a separate package in melpa. I really think the Emacs ecosystem would benefit from this package.

Thanks in advance!

**Comment by skeeto** [comment]
Ultimately that would probably be a good thing, but I have two selfish
objections, most important first:

1. Elfeed has no dependencies outside of Emacs. This is incredibly
   convenient for development, testing, and stability -- so much so that
   I've become very hesitant to have any dependencies in any of my
   packages. Putting xml-query on Melpa would essentially mean moving it
   out of Elfeed and making it a dependency.

2. By not encouraging people to use it, I don't have to worry much about
   supporting the various use cases. It only has to work exactly well
   enough for Elfeed's needs.

Do you have a particular use in mind?

**Comment by marsam** [comment]
Hi:

Sorry for the late response.

> 1. Elfeed has no dependencies outside of Emacs. This is incredibly convenient
>    for development, testing, and stability -- so much so that I've become very
>    hesitant to have any dependencies in any of my packages. Putting xml-query
>    on Melpa would essentially mean moving it out of Elfeed and making it a
>    dependency.

I think this can be solved separating the melpa recipe

+ current

    ``` emacs-lisp
    (elfeed :repo "skeeto/elfeed"
            :fetcher github)
    ```

+ New recipes

    ``` emacs-lisp
    (elfeed :repo "skeeto/elfeed"
            :fetcher github
            :files (:defaults
                    (:exclude "xml-query.el")))
    ```

    ``` emacs-lisp
    (xml-query :repo "skeeto/elfeed"
               :fetcher github
               :files ("xml-query.el"))
    ```

This approach is used by [ivy recipe][] to maintain `swiper` and `counsel` as separated packages.

If you like this idea I can make a pull request to melpa with the new recipes.

> Do you have a particular use in mind?

Nothing in particular, I just want to use `xml-query.el` for interacting with
xml based services.

[ivy recipe]: https://github.com/melpa/melpa/blob/44a382a3/recipes/ivy

**Comment by skeeto** [comment]
For this recipe to work, I guess I'd need to add a version header to
xml-query.el, and add xml-query as a dependency in elfeed-pkg.el? For
MELPA stable, I guess this also means the xml-query and elfeed version
numbers are kept in lock-step, since they share tags. This appears to be
the case with Ivy's components, and that's how it works with elfeed-web.
It also means there may be a brief period where the Elfeed package is
broken, until both Elfeed and the recipe are in sync.

**Comment by alphapapa** [comment]
Curious, is there any reason to proceed with this?  I just experimented with `esxml-query`, and it works very well, so is there any benefit that this library could provide over it?  Thanks.

**Comment by skeeto** [comment]
@alphapapa You're right. Now that esxml exists, I'd rather people rely on that package instead of a subset of Elfeed. It doesn't (yet?) have the cool compile-to-byte-code stuff, but it's always going to be more feature-complete. I don't want to add any features to xml-query unless Elfeed needs it.

So I'm just going to close this and say, "Use esxml."
