### ISSUE TITLE
Elfeed fails to open entry

### ISSUE THREAD

**Issue by jabranham** [skeeto/elfeed#199]
Cambridge nixed their RSS feeds for their journals, so I have them email journal updates to an email address which then auto-generates an RSS feed. Here's the feed link: https://zapier.com/engine/rss/1846337/alex/ (yes, I've tried to get Cambridge to send plain-text emails but they seem to ignore that preference setting.)

However, trying to open an entry from that in elfeed results in `url-expand-file-name: Wrong type argument: char-or-string-p, nil`.

**Comment by skeeto** [comment]
Elfeed was mistakenly setting the base URL to "nil" which was then
confusing shr (shr should really be more graceful about it) when the
link was relative (which it's not supposed to be). Should be fixed now.

Though because, as you probably noticed, the feed is a mess, the link
Elfeed was trying to insert still won't make sense, but at least it will
display the content.

**Comment by jabranham** [comment]
That was super fast! Much appreciated. 

Yes, the feed is an absolute mess. I keep  trying to get them to send plain text in the hopes that it's better but they don't seem to honor that setting. For now, it's enough just to be notified when they publish something new. 

Thanks again!
