### ISSUE TITLE
memory leak downloading enclosure

### ISSUE THREAD

**Issue by motherload** [skeeto/elfeed#215]
Hi. Everytime I try to download some enclosure, usually an mp3 file from some podcast, elfeed quickly eats up my ram. All 8 GiB of it. I'm using the latest version from melpa that I updated today, but this was happening in the previous version as well.

**Comment by skeeto** [comment]
I'm assuming the enclosure isn't anywhere nearly as large as 8GB. The
function that actually downloads enclosures is url-copy-file. If you use
this function directly, do you see the same memory usage? For example:

  (url-copy-file "http://skeeto.s3.amazonaws.com/share/julia-256.mp4" "~/x.mp4" t)

Also, do you have the "async" package installed? This is used to
download files in the background if it's available. It's possible
there's a bad interaction with these two things.

Mostly I suspect this is a bug in Emacs rather than with Elfeed.

**Comment by motherload** [comment]
You were right, it was a bug in emacs, probably something in the async package. Your code worked fine. Removed async and it worked. Reinstalled async and it's working again. Closing.

P.S. Thanks for the quick answer!
