### ISSUE TITLE
Issue in emacs 26.0.50: Wrong type argument: avl-tree-

### ISSUE THREAD

**Issue by therockmandolinist** [skeeto/elfeed#217]
The message says:
`elfeed-db-load: Wrong type argument: avl-tree-, [cl-struct-avl-tree- [nil nil nil 0] elfeed-db-compare]`. 

Another similar one when trying to run `elfeed-update`:
`Error running timer ‘elfeed-curl--fail-callback’: (wrong-type-argument avl-tree- [cl-struct-avl-tree- [nil nil nil 0] elfeed-db-compare]) [2 times]`

**Comment by skeeto** [comment]
This is due to the printed form of defstruct changing in the upcoming 
Emacs 26. Currently an Elfeed database created by Emacs 25 and earlier 
cannot migrate to Emacs 26 and later. You can work around this by 
creating a new, empty database. This can be done by deleting your 
database index file either when Emacs isn't running or immediately after 
executing M-x elfeed-db-unload. See #207.

**Comment by titaniumbones** [comment]
I know this is closed, but I just want to ask -- does this mean my whole history dissappears  on upgrade? WOuld love to get it back somehow if htat's possible...

**Comment by skeeto** [comment]
It's only closed because it's essentially a duplicate of #207. I'd like 
to either:

1. Automatically convert the old format to the new. This includes both 
Elfeed's structs as well as avl-tree's. This would be a one-way process 
since it's not feasible to convert backwards. The Emacs 25 reader won't 
accept the new syntax.

2. Drop cl-defstruct and use a custom macro that restores the original 
behavior (see fb57254). The new Emacs 26 cl-defstruct is about 15%–20% 
slower than it is in Emacs 25, so this would be the fastest option and 
require no conversion. This works except for avl-tree, which uses the 
new cl-defstruct regardless of what Elfeed does.

**Comment by titaniumbones** [comment]
Thanks for hte pointer to #207; the brute-force hack reported there worked for me, so I'll use that for now, and hopefully it doesn't become unworkable any time soon!

**Comment by hisnawi** [comment]
Skeeto, I did delete both index and data directory but I still get this error when trying to exit emacs:

`elfeed-db-load: Wrong type argument: avl-tree-, [cl-struct-avl-tree- [nil nil nil 0] elfeed-db-compare]
`

**Comment by skeeto** [comment]
Did you re-byte-compile/re-install Elfeed after switching to Emacs 26? 
When you move between Emacs releases you must to reinstall all of your 
M/ELPA packages from scratch and clear out .elc files that were compiled 
with the previous version. Old .elc files will have old bytecode and old 
macros that are unlikely to be correct across releases.

**Comment by hisnawi** [comment]
uninstalling and then reinstalling elfeed fixed it. Thanks.

**Comment by avkoval** [comment]
elfeed-db-load: Wrong type argument: avl-tree-, [cl-struct-avl-tree-
I've removed index, data directories, removed all elpa packages and installed them again, then removed elfeed from packaged and installed it again, nothing helps yet.

**Comment by skeeto** [comment]
Make sure Emacs is completely exited when you delete the old database. 
Otherwise it will just be restored by Emacs, since it's still resident 
in memory.

Alternatively, you can call cl-old-struct-compat-mode in your config, 
which allows backwards compatibility with the pre-Emacs 26 database 
format.
