### ISSUE TITLE
(35) SSL connect error. The SSL handshaking failed.

### ISSUE THREAD

**Issue by Ambrevar** [skeeto/elfeed#230]
I constantly get an SSL connect error on some specific feeds, such as
https://sachachua.com/blog/category/emacs-news/feed/.

Other HTTPS feeds such as https://hackernoon.com/feed are fine. Any clue what's happening?

**Comment by Ambrevar** [comment]
Turns out that i can use HTTP for sachachua.com and it works. A better example is http://golangnews.com/index.xml or https://golangnews.com/index.xml: they both yield the same error.

**Comment by skeeto** [comment]
I don't get errors for either of these URLs on any of the three networks 
and computers that I've tested it on. This suggests it's a problem local 
to your machine or network. The key piece of information is that "35" 
which is curl's CURLE_SSL_CONNECT_ERROR:

> A problem occurred somewhere in the SSL/TLS handshake. You really want 
> the error buffer and read the message there as it pinpoints the 
> problem slightly more. Could be certificates (file formats, paths, 
> permissions), passwords, and others.

Since you're using the curl backend (good!), it will be easier to test 
and debug. You will be seeing the same errors on the command line from 
curl as you see in Elfeed, so you can test it outside of Elfeed. If you 
want to reproduce the exact command that Elfeed is using when it runs 
curl, evaluate elfeed-curl--args:

    (elfeed-curl--args "https://golangnews.com/index.xml" nil)

Just running curl directly, outside of Elfeed, try to figure out how to 
fix the issue for curl. There are a few possibilities from here:

1. You've got a local SSL/TLS certificate configuration issue, which you 
need to solve independently of Elfeed. Can you visit these URLs in all 
of your browsers without issue?

2. You're experiencing a man-in-the-middle attack on the network. This 
is sometimes the case with hotel wifi and corporate networks. Your 
network may be preventing you from establishing HTTPS connections.

3. Your local network is misconfigured, which manifests like possibility 
2 above. This is often a problem on hotel and corporate networks. An 
internet search suggests a common cause of error 35 is a misconfigured 
IPv6 network. Try adding "-4" to curl's command line options to force 
IPv4 (or alternatively "-6" to force IPv6, if it's IPv4 that's the 
problem):

    (push "-4" elfeed-curl-extra-arguments)

**Comment by Ambrevar** [comment]
>     (elfeed-curl--args "https://golangnews.com/index.xml" nil)

It does nothing for me.  Should I run this in a particular context?

I tried from commandline

	$ curl https://golangnews.com/index.xml

And I get the same error indeed.

I'm on a residential gateway, so a MitM attack seems unlikely.

Browsers: I have tried with Qutebrowser and EWW, both work fine and
validate the certificate properly.

I'm thinking certificates now.  I'm on a new Gentoo install, I could
have done something wrong with it.

**Comment by Ambrevar** [comment]
After further investigation, I'm quite sure this is a misconfiguration
on my side, I probably need to add some USE flags to openssl.  Here is
what I get from the client:

```
$ openssl s_client -connect golangnews.com:443
CONNECTED(00000003)
139770155599512:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 194 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1501480613
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by Ambrevar** [comment]
Found this: https://unix.stackexchange.com/questions/263758/how-to-fix-curl-sslv3-alert-handshake-failure-on-gentoo

Linking to a Gentoo bug: https://unix.stackexchange.com/questions/263758/how-to-fix-curl-sslv3-alert-handshake-failure-on-gentoo

**Comment by Ambrevar** [comment]
I've built curl against gnutls instead of openssl and the issue is gone.
@skeeto: Do you think that could be problematic?

**Comment by skeeto** [comment]
I don't know of any technical issues with this. The only issue I know 
about is licensing: OpenSSL's license is not GPL-compatible, so linking 
libcurl against OpenSSL makes that libcurl build not GPL-compatible. 
This doesn't matter in your case since you're not redistributing 
anything.

**Comment by Ambrevar** [comment]
Great, closing this then.

**Comment by meedstrom** [comment]
Hi Ambrevar. I'm having a seemingly identical issue. My Emacs is installed thru Guix, as I know yours to be, that's probably related? Want to show me how you fixed it, if you remember?

Some failing blogs with error 35:
* https://www.ketotic.org/feeds/posts/default
* https://evidence.blogg.lu.se/atom
* https://www.sumsar.net/atom.xml

**Comment by Ambrevar** [comment]
I use Guix System and I've never experienced this issue ever since.
(The original post is about Gentoo.)
I'm guessing that you are running Guix on a foreign distro.  The wrong curl / certificate path might be the problem for you.  I suggest you ask on the help-guix mailing list, you'll probably find more help there.

**Comment by meedstrom** [comment]
Thank you! 

Indeed I am on Debian. Doing `guix install curl nss-certs` and reloading the guix profile fixed some feeds. The remaining sites appear to simply not support https in the first place (my bad) so I changed them to http.

**Comment by snowman** [comment]
#### Make sure you are not running curl under proxy:

```lisp
(setenv "HTTP_PROXY" nil)
(setenv "HTTPS_PROXY" nil)
```
