### ISSUE TITLE
Format specifier doesn’t match argument type

### ISSUE THREAD

**Issue by sjLambda** [skeeto/elfeed#234]
I get this error

    image-multi-frame-p: Format specifier doesn’t match argument type

For an [item from Slashdot](https://developers.slashdot.org/story/17/08/18/2231248/google-and-propublica-team-up-to-build-a-national-hate-crime-database).

It looks like any normal item though, both on online and in elfeed-search screens. See the screenshot below:

![elfeederror](https://user-images.githubusercontent.com/15698764/29487376-c7b6b9bc-84ac-11e7-86db-3c6a355b64de.png)

**Comment by skeeto** [comment]
Where do you see this error? In the minibuffer? When exactly do you see 
it (e.g. viewing the article, or seeing it listed in the search buffer)? 
Try setting debug-on-error to t so that hopefully we can get a complete 
backtrace.

I'm unable to reproduce the issue running in an plain Emacs session. See 
if you can reproduce it without your config, in order to verify if the 
problem is in Elfeed or in the way it's configured. It's really easy:

1. Clone the Elfeed repository and cd into it.
2. Run "make" to byte-compile all the sources.
3. mkdir /tmp/testhome
4. HOME=/tmp/testhome emacs -L . -l elfeed.elc -f elfeed
5. "M-x elfeed-add-feed" and subscribe to the offending feed.

I used this feed:

http://rss.slashdot.org/Slashdot/slashdotDevelopers

And everything was working fine as far as I could tell.

**Comment by sjLambda** [comment]
Where is the error?
Error flashes in the minibuffer and is logged to the Messages buffer as well.

When?
M-x elfeed-search-show-entry or up on RET on an item list on elfeed-search screen

Which entries?
Mixed. Not just one site, but only "some" items from certain sites. For example, I may have 4 entries from slashdot, but only one shows this error. The others that came with that update display fine.

As for testing barebones config, results will be in a follow up email.

**Comment by sjLambda** [comment]
I was able to reproduce the same error in plain Emacs. Followed your instructions above.  Same error, tested only one site.

FWIW, I'm using: GNU Emacs 26.0.50 (build 1, x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1611)) of 2017-08-19

![plainemacs](https://user-images.githubusercontent.com/15698764/29489802-fa60598c-84dd-11e7-8787-5a95dae95c6e.png)

**Comment by skeeto** [comment]
I still can't reproduce it with the latest development version of Emacs 26 (1c382c0) in Debian 9. Judging from the `image-multi-frame-p`, I suspect this is a bug somewhere in the image library bindings of your specific Emacs build. It seems like it may be complaining about the little share icons in the entry content. These are PNGs, but perhaps it's still inspecting them for multiple frames?

This is a bit of a long shot, but if you evaluate this in your scratch
buffer, do you get the error?

~~~el
(require 'shr)

(shr-insert-document
 '((div ()
        (img ((src . "https://a.fsdn.com/sd/twitter_icon_large.png")))
        (img ((src . "https://a.fsdn.com/sd/facebook_icon_large.png")))
        (img ((src . "http://www.gstatic.com/images/icons/gplus-16.png"))))))
~~~

Another thing to try is disabling images to see if that makes the error
go away: 

~~~el
(setq shr-inhibit-images t)
~~~

If the first test code displays the error, or the second test stops the
error from occurring, then it's definitely a bug in Emacs itself, or at
least in your specific build.

**Comment by sjLambda** [comment]
(setq shr-inhibit-images t) stopped the error for now. I can at least read the text part of the feeds. Thanks.

As for the image error in Emacs, I'll have to look into it later. Since my emacs compiles with Imagemagick by default, I see that that lib had some fixes recently for png compression. Perhaps a permanent solution is there.
