### ISSUE TITLE
elfeed doesn't update all feeds

### ISSUE THREAD

**Issue by KrullBorg** [skeeto/elfeed#235]
hi i'm trying elfeed as my new rss reader

i imported opml from "tiny tiny rss" (about 200 feeds) and i'm using elfeed-org
but when i try to update feeds (with G), elfeed stop to download feeds after a while
it says "151 feeds pending, 0 in process" (the number of pending feeds it's not always the same; and i tried to wait a lot to see if it restarts)
if i re-run G, the number of pending feeds grows and after a while it stops again (with an higher number of pending feeds respect to the first time)
in *elfeed-log* i found only errors relative to invalid feeds (i know that i have these feeds)
i'm a noob also of emacs so i don't know what info you need
thanks in advance

**Comment by skeeto** [comment]
Are you using the curl backend? Check with "C-h v elfeed-use-curl", 
inspecting the variable for t or nil. This backend is automatically 
enabled if Elfeed discovers the curl command line program on startup, 
and typically you don't want to set this variable yourself.

I strongly recommend that you use the curl backend. Otherwise Elfeed 
falls back to Emacs' built-in url-retrieve function, which is _really_ 
buggy and runs into this particular issue all the time. It's why I wrote 
the curl backend. All you need to do is have curl installed in your 
PATH. If the PATH is inconvenient, you can set elfeed-curl-program-name 
to curl's absolute path before loading Elfeed.

If you're not using the curl backed, you can use "M-x elfeed-unjam" to 
reset Emacs' built-in url-queue by aborting all pending fetches. Then 
try fetching again. That's about the best you can do since the bug lies 
inside Emacs itself.

If you _are_ using the curl backend and still experiencing this, then 
I'm interested in seeing your OMPL and the contents of your 
"*elfeed-log*" buffer, which will contain more detailed information 
about what's going on.

**Comment by KrullBorg** [comment]
thanks!!! now with curl it seems to work very well

**Comment by alphapapa** [comment]
Guess this can be closed.  :)
