### ISSUE TITLE
Possible to search by feed, rather than entry, URL?

### ISSUE THREAD

**Issue by joewreschnig** [skeeto/elfeed#237]
Is it possible to search by feed URL, rather than feed name or entry URL?

My situation is that I'm trying to wire Firefox's RSS handler up to Elfeed - Firefox passes my script a URL, which uses emacsclient to add it to elfeed; I'd like to set the elfeed filter to show that new feed. But at the time I add it (and want to set the filter) I don't have the name, only the URL.

**Comment by skeeto** [comment]
This is a neat idea. There's no reasonable way to add the feed URL to 
the filter match without directly modifying Elfeed since this is coupled 
tightly with all the filter stuff. However, there's still a reasonable 
solution.

As long as you've fetched at least once, you can convert a feed URL to a 
feed name trivially:

    (elfeed-feed-title (elfeed-db-get-feed my-feed-url))

Then you can shove the resulting string into the filter, which will 
match it by feed title. If there are spaces in the name then it will be 
a little less precise (filters split on spaces). If this is an issue, a 
hack to work around this would be to replace the spaces with the regexp 
equivalent: "\s-".

**Comment by joewreschnig** [comment]
I haven't fetched it once yet, though. I guess I could keep the adding script around until the fetch completes, but that seems nontrivial using the existing hook system - I'd have to register hooks on success and all the errors, filter out the feeds I'm not interested in, and unhook everything once it's done, plus probably some manual timeout logic.

[It seems like the feed URL is used as the feed ID, which in turn is easy to add to the fields being checked for each entry.](https://github.com/joewreschnig/elfeed/commit/8ade9efaf5f925e4e26829c825e8281d55f86bb0) Would you be open to a change like that?

Another option might be a special syntax, e.g. `=<url>` to match exactly feed / entry URL.

**Comment by skeeto** [comment]
The feed URL being separate from the feed ID is vestigial from when I 
thought these values might differ. It reflects Atom's model where the 
same feed might be available from two different URLs. This got 
complicated fast, so I punted on the idea.

I'm hesitant to expand the fields searched by the regexp matches just 
for this one use case. That change could over-select for other existing 
uses.

So instead I ran with your "=<url>" syntax idea. It's actually 
"=<regexp>", and you should see this commit now. I removed feed title 
matching from the plain regular expression filter, so users will need to 
use the =X syntax if they want to match anything about feeds.

**Comment by joewreschnig** [comment]
This works perfect, thanks!
