### ISSUE TITLE
error in process sentinel: elfeed-curl--parse-write-out: Search failed:

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#248]
Hi Chris,

I've been seeing this error sometimes, which seems to be accompanied with stuck processes (it still says "1 in process ...", and as I refresh more times in the future, sometimes the number of stuck processes increases):

```
error in process sentinel: elfeed-curl--parse-write-out: Search failed: "=d/0iSnFkRcu<KhO>vSL+="
error in process sentinel: Search failed: "=d/0iSnFkRcu<KhO>vSL+="
```
The string is different each time.  Elfeed continues to work fine otherwise, but I don't know if certain feeds are getting stuck, or if it's random.

I'm using elfeed 20171103.737 with the curl backend.

Thanks for your help.

**Comment by alphapapa** [comment]
BTW, I've noticed that it seems to be a transient problem.  e.g. if I use `unjam` and then refresh all the feeds again, they'll typically complete without error.  Or I can even refresh without unjamming first, and usually they'll all complete without error, but leaving the originally stuck ones still stuck until I unjam.

Thanks.

**Comment by skeeto** [comment]
What operating system are you using? I wonder if something strange is 
going on with the arguments passed to curl, like they're being parsed by 
a shell. In your specific example here there happens to be a balanced 
pair of angle brackets. Is this a typical pattern when it fails? Those 
are randomly-generated strings being used as boundaries between curl 
responses and don't have any meaning to them.

**Comment by alphapapa** [comment]
I'm on Linux, on Ubuntu 14.04, using Curl 7.35.0-1ubuntu2.12.

I don't think the `<>` are a problem.  Here are two more of the boundary strings that I got from the messages buffer:
```
"=2q@MGiTvQcyha~cXg$>u="
"=scsf9z~~87NAZE|pPNN-="
```
Thanks.

**Comment by alphapapa** [comment]
Just a thought: I wonder if the problem is that the curl request failed, and rather than that being detected, the string is still searched for, which doesn't exist because the request failed.

**Comment by skeeto** [comment]
That's possible. If curl exits with code 0, then Elfeed will attempt to 
parse the --wirte-out token. Perhaps there's a case where the request 
fails, and so the --write-out token isn't written, but curl still exits 
with 0.

**Comment by skeeto** [comment]
I'm finally able to reproduce this issue. I'm seeing it consistently on 
FreeBSD 11.1-STABLE, armv6 (Raspberry Pi 2), with curl 7.57.0 built from 
ports and Emacs 25.3 built from ports. Emacs is reporting success to the 
sentinel from curl (i.e. "finished\n") but the content and --write-out 
are missing. Someone's lying to Elfeed.

I added a write-file at the beginning of the elfeed-curl sentinel to 
immediately dump the buffer filled by curl before any further action 
takes place. I also fired up DTrace so that I could compare this to what 
curl _actually_ produced, as well as monitor the actual exit code. I 
trust DTrace more than I trust Emacs.

Conclusion: This is definitely some kind of nasty Emacs bug. It's simply 
truncating inferior process output. Nothing more. DTrace shows curl did 
everything write, but my write-file probe within Emacs doesn't see all 
of the output. Perhaps this bug is limited to Emacs 25.3 or to specific 
builds. If you're running Ubuntu 14.04 does this mean you're using Emacs 
24.3? I've never experienced this in Debian, currently with Emacs 25.1.

Most of the time something goes wrong, the curl buffer is completely 
empty in Emacs — despite DTrace indicating curl provided all the 
appropriate output — but occasionally it's truncated immediately after 
the HTTP header, after the blank line. This is a suspiciously consistent 
place for it to get stuck, and it's starting to sound familiar. But 
what's more obvious is that, according to DTrace, curl is operating line 
buffered, and that's because Emacs is connected it to a PTY.

That's when the light bulb turned on. Emacs' PTY usage is buggy as hell 
and has been for _years_. I've got bug reports for this stuff dating 
back to 2013. It caused me all sorts of issues when I wrote EmacSQL. On 
top of it all, Emacs should never be using PTYs like this in the first 
place. It's an awful default. Fortunately it's trivial to fix: set 
process-connection-type to nil when starting curl.

BAM! With that done, this Emacs bug seems to be completely resolved. 
Even better, ELFEED IS SO MUCH FASTER AT FETCHING FEEDS!!! Holy moly, I 
should have done this years ago. There's a very noticeable difference 
in performance even on my laptop. Everyone will benefit from this fix.

So, thanks for reporting this bug and making Elfeed a ton better!

**Comment by alphapapa** [comment]
Hi Chris,

That's great news!  I'm really glad you were able to track it down.  Thanks for digging into it.  

For reference, I am on Ubuntu 14.04, but I'm using Emacs 25.2 that I built from newer source packages.  It's the only version I've used Elfeed with so far.  It does seem strange that it was so hard to reproduce, and that other users aren't reporting it.  I wonder if it's an issue with underlying libraries.  

Anyway, thanks for fixing this.  Let me know if I can help further.

**Comment by alphapapa** [comment]
By the way, since this is a bigger issue that affects Emacs subprocesses, I wonder if if you should write a blog post about it...  :)

**Comment by skeeto** [comment]
Debugging Emacs or: How I Learned to Stop Worrying and Love DTrace
http://nullprogram.com/blog/2018/01/17/

I had just broken ground on that article when you suggested it. ;-)

**Comment by alphapapa** [comment]
LOL, I should have known.  :)  Thanks.
