### ISSUE TITLE
Feeds update not so fast

### ISSUE THREAD

**Issue by sgtpep** [skeeto/elfeed#25]
Currently I'm subscribed to 78 feeds. The `elfeed-update` takes 2m 45s to fetch them all one by one.

My initial workflow for feed updating was: 1) Got time to read new feeds, 2) If there are no new feeds, start elfeed-update. 3) Wait almost 3 minutes. 4) Read. Then I became familiar with `run-at-time` function, and set up auto-update. So the updating is still long, but it runs in background.

Still, is there any chance to make it faster? What is the bottleneck of this process: fetching, parsing, or storing? If first is the problem, than may be it could be better to use curl/wget, if available?

**Comment by skeeto** [comment]
Closing since this was addressed by a number of major changes:

* [Domain-Specific Language Compilation in Elfeed](https://nullprogram.com/blog/2016/12/27/)
* [Faster Elfeed Search Through JIT Byte-code Compilation](https://nullprogram.com/blog/2016/12/11/)
* [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/)
