### ISSUE TITLE
Should db-load be run when elfeed is run?

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#253]
Hi Chris,

While debugging an entry hook, I came up with this function to let me delete entries from a feed, so I could refresh them and have the entry hook be reapplied to them:
```el
(defun ap/elfeed-delete-entries (pred)
  "Delete entries from `elfeed-db-index' and `elfeed-db-entries' that PRED returns non-nil for.
PRED is called with one argument, the entry."
  (let ((size-before (ht-size elfeed-db-entries)))
    (cl-loop for key being the hash-keys of elfeed-db-entries
             using (hash-values entry)
             when (funcall pred entry)
             do (progn
                  (avl-tree-delete elfeed-db-index (elfeed-entry-id entry))
                  (ht-remove elfeed-db-entries key)))
    (a-list 'before size-before
            'after (ht-size elfeed-db-entries))))
```
Used like:
```el
(ap/elfeed-delete-entries (lambda (entry)
                            (equal (elfeed-entry-feed-id entry) "https://example.com/index.rss")))
```
Anyway, while doing this I ended up unloading and reloading the database several times (before I got the function right, after which that wasn't necessary).  I noticed that the database does not seem to be loaded automatically after `elfeed-db-unload`, because I had to run `elfeed-db-load` manually for changes in the database file to be reflected in the entries, even after killing the `*elfeed-search*` buffer and running `elfeed`.

I'm likely misunderstanding something, but I wonder: should the database be loaded when `elfeed` is run?

Thanks.

**Comment by skeeto** [comment]
Some database functions begin by calling elfeed-db-ensure, which loads 
the database only if necessary. Some database functions don't need this 
since they can only meaningfully be called after the database has 
already been loaded. For example, any function that operates on an entry 
or feed object is free to assume the database is already loaded because 
the object had to come from somewhere.

Things get a little weird with the search buffer, since it maintains a 
little bit of its own state: buffer-local variables and buffer contents. 
That state becomes stale after elfeed-db-unload. It will call database 
functions with these stale objects, and they won't know they're stale. 
Per above, these functions don't call elfeed-db-ensure since it's 
assumed the objects are from a loaded database.

So the search buffer state state is stale, so it should be "unloaded" 
too. However, elfeed-db-unload is a core function that isn't aware of 
the search buffer or other such user interface things. It's the sort of 
circular dependency to be broken with a hook.

**Comment by alphapapa** [comment]
Thanks!
