### ISSUE TITLE
Stack overflow in Regexp matcher

### ISSUE THREAD

**Issue by impaktor** [skeeto/elfeed#260]
Every other day / week, elfeed fails to update, and throws a "Stack overflow in Regexp matcher". 
My ~/.elfeed/index file is at those times empty, and only by removing it can I get it working again, but now I have to go through all the backlog and re-mark all read feeds as read.

1. any idea what is causing this?

2. any idea how I can make a new index file that goes through _all_ previously fetched feeds. Seems like the new index doesn't look at previously downloaded content, instead it fetches feeds anew from online.

**Comment by skeeto** [comment]
What version of Emacs and Elfeed are you using? Also, could you provide 
a stack trace for the error? If you aren't getting one already, you 
could "M-x toggle-debug-on-error" before it happens so that you do. That 
would be the most useful piece of information for tracking down the 
regexp causing the issue.

This issue sounds a lot like #161. Perhaps there's something in your 
configuration that's trying to scan the index contents with a regexp 
when it's read in. Some things to check:

* Do you have any entries in magic-mode-alist (default: nil)?
* What is your magic-mode-regexp-match-limit (default: 4000)?

I'm not quite sure what you mean about fetching anew, but whatever 
you're seeing is probably a side effect of deleting your index file. 
That's how Elfeed keeps track of everything it's seen.

**Comment by impaktor** [comment]
I'm on GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-04, and Elfeed 20171224.1850 from MELPA.

Evaluation `magic-mode-alist` returns `nil`, and `magic-mode-regexp-match-limit` is set to `4000 (#o7640, #xfa0, ?ྠ)`

> I'm not quite sure what you mean about fetching anew

Granted my understanding of elfeeds inner working is zero, but I assumed the feeds are stored in the data-folder, and the index file indexes those. I assumed that removing the faulty index files it will loose track of all the old feeds I've read? So I was wondering if there was a way for the index file to find all downloaded feeds, or maybe this is what it does when it's removed, and created anew?

> This issue sounds a lot like #161. 

I'm not sure what that entails, but my emacs is set to default buffers to org-mode, rather than fundamental-mode, if that could have something to do with the bug?:
```emacs-lisp
;; set default mode for unknown files
(setq-default major-mode 'org-mode)
```

I've now set: `(setq debug-on-error t)`, so next time it happens, I will then get a trace to post? Is anything else I should do when I get the stack overflow to trace the error?

**Comment by impaktor** [comment]
Got a stack trace, but this time it didn't corrupt my index-file:
```emacs-lisp
Debugger entered--Lisp error: (error "Stack overflow in regexp matcher")
  looking-at(".*:ARCHIVE:")
  org-cycle-hide-archived-subtrees(all)
  org-set-startup-visibility()
  org-mode()
  set-buffer-major-mode(#<buffer index>)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil nil)
  find-file-noselect-1(#<buffer index> "~/.elfeed/index" :nowarn nil "~/.elfeed/index" (16014784 65025))
  find-file-noselect("/home/vandelay/.elfeed/index" :nowarn)
  elfeed-db-load()
  elfeed-db-ensure()
  elfeed-search--update-list()
  elfeed-search-update(:force)
  elfeed-search-mode()
  elfeed()
  funcall-interactively(elfeed)
  call-interactively(elfeed record nil)
  command-execute(elfeed record)
  execute-extended-command(nil "elfeed" "elf")
  funcall-interactively(execute-extended-command nil "elfeed" "elf")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I'll see if I can post another, once I get a strack trace that actually does corupt the index-file.

**Comment by skeeto** [comment]
Thanks, I think this stack trace answers the question. The problem is 
with org-mode as the default mode, it's enabled when loading the index 
with find-file-noselect, and it attempts to parse the buffer containing 
the index, which fails abysmally as you've seen. The only way to fix 
this is to override the default value of major-mode, which isn't quite 
as simple as a let. I've pushed a commit that does it with cl-letf.

I also considered temporarily overriding the definition of 
after-find-file to a dummy function, since Elfeed basically doesn't want 
it this function do anything when loading the index (load buffer-local 
variables, set the major mode, etc.). I think it's a flaw in Emacs that 
there's no way to prevent after-find-file from running without also 
disabling buffer conversion (e.g. decoding UTF-8, etc.). Elfeed really 
does need the latter.

**Comment by impaktor** [comment]
Thanks!

Just to make sure, are you saying elfeed will now play nice with `setq-default major-mode`? Or is it still recommended to not set, and default to fundamental-mode?

**Comment by skeeto** [comment]
It should work fine now even if you do something nutty with the default 
value for major-mode. I personally think setting it to org-mode is a bit 
much since that's such a heavyweight mode that's so aggressive with the 
buffer, but at least Elfeed shouldn't care anymore. There might still be 
an issue loading entry content (i.e. elfeed-ref-archive-load) if Emacs 
also tries to set the buffer to org-mode while it contains other sorts 
of database content, but I haven't tested that yet.
