### ISSUE TITLE
Problems with elfeed-update on OS X

### ISSUE THREAD

**Issue by fleimgruber** [skeeto/elfeed#261]
I am using Emacs 25.3 with homebrew, spacemacs develop branch and elfeed 2.2.0.  Curl is 7.57.0 also via homebrew and specified via `elfeed-curl-program-name`.

On `elfeed-update` I get the following in the `*elfeed-log*` buffer:
```
[2018-01-05 10:02:30] [info]: Elfeed update: January  5 2018 10:02:30 CET
[2018-01-05 10:03:20] [error]: http://rss.golem.de/rss.php?feed=ATOM1.0: "(28) Operation timeout."
[2018-01-05 10:03:20] [error]: http://planet.emacsen.org/atom.xml: "(28) Operation timeout."
[2018-01-05 10:03:20] [error]: https://www.masteringemacs.org/feed/: "(28) Operation timeout."
[2018-01-05 10:03:20] [error]: http://planetpython.org/rss20.xml: "(28) Operation timeout."
[2018-01-05 10:03:21] [error]: http://planet.scipy.org/rss20.xml: (void-function nil)
```

And updating is stopped after the `(void-function nil)`.

I read in older issues that this is most likely caused by misconfiguration on the OS side, e.g. gnutls.  I did some manual tests for curl and it seems to work there.  I tried to edebug `elfeed-curl-retrieve` but could not pin the error down.  Any tips / suggestions on how to debug this?

**Comment by skeeto** [comment]
I should really add some mechanism to optionally get a stack trace for 
hard lisp errors rather than swallow them and note it in the log. That's 
a reasonable default, but bad for debugging.

What's likely the case for the final error is a nil hook set by your 
configuration. Places for you to check after this error or just after 
your config is loaded:

* elfeed-http-error-hooks
* elfeed-parse-error-hooks
* elfeed-update-init-hooks
* elfeed-new-entry-hook
* elfeed-new-entry-parse-hook

These can each be nil, but they should not be a list that *contains* 
nil.

Timeouts aren't *that* uncommon, but, if they happen a lot, it's an 
indication there's an issue with your local network. Maybe it's heavily 
throttled, or maybe there's some packet inspection middleware that's 
slowing everything down (common on corporate networks). You can try 
increasing the timeout (elfeed-set-timeout, default 30s) or reducing the 
number of feeds fetched in parallel (elfeed-set-max-connections, default 
16).

In investigating this I did find a bug introduced in fb3fbf1 (#259). The 
Planet Python feed currently has an item with an empty link tag. That's 
invalid for RSS 2.0, but, despite this, Elfeed handled this issue 
gracefully until recently. This fix will probably make your last error 
go away for now, but I still suspect there's a misconfiguration on your 
end. (There's also a bug in the Elisp debugger triggered by this Elfeed 
bug which made it annoying to debug.)

**Comment by fleimgruber** [comment]
Thanks for the quick and comprehensive answer.  Indeed, `elfeed-new-entry-hook` evaluates to `(nil elfeed-goodies/html-decode-title)` and it was due to a spoiled `add-hook` on my side.  Sorry for the noise.  Keep up the good work!

**Comment by skeeto** [comment]
Your configuration error indirectly uncovered a legitimate bug, so this 
wasn't just noise. Thanks for bringing it to light!
