### ISSUE TITLE
Error: void-function closure

### ISSUE THREAD

**Issue by kaushalmodi** [skeeto/elfeed#269]
Hello,

The recent commits are causing this failure when I load Org, like tangling an Org file.

I was tangling an Org file, and I got:

```
Debugger entered--Lisp error: (void-function closure)
  (closure (t) nil (if (version< (org-version) "9.0") (with-no-warnings (org-add-link-type "elfeed" (function elfeed-link-open)) (add-hook 'org-store-link-functions (function elfeed-link-store-link))) (with-no-warnings (org-link-set-parameters "elfeed" :follow (function elfeed-link-open) :store (function elfeed-link-store-link)))))
  (funcall (closure (t) nil (if (version< (org-version) "9.0") (with-no-warnings (org-add-link-type "elfeed" (function elfeed-link-open)) (add-hook 'org-store-link-functions (function elfeed-link-store-link))) (with-no-warnings (org-link-set-parameters "elfeed" :follow (function elfeed-link-open) :store (function elfeed-link-store-link))))))
  (closure (t) nil (funcall (closure (t) nil (if (version< (org-version) "9.0") (with-no-warnings (org-add-link-type "elfeed" (function elfeed-link-open)) (add-hook 'org-store-link-functions (function elfeed-link-store-link))) (with-no-warnings (org-link-set-parameters "elfeed" :follow (function elfeed-link-open) :store (function elfeed-link-store-link)))))))()
  eval-after-load(org (funcall (closure (t) nil (if (version< (org-version) "9.0") (with-no-warnings (org-add-link-type "elfeed" (function elfeed-link-open)) (add-hook 'org-store-link-functions (function elfeed-link-store-link))) (with-no-warnings (org-link-set-parameters "elfeed" :follow (function elfeed-link-open) :store (function elfeed-link-store-link)))))))
  eval-buffer(#<buffer  *load*> nil "/home/kmodi/.emacs.d/elpa_27/elfeed-20180219.1340/elfeed-link.el" nil t)  ; Reading at buffer position 2620
  load-with-code-conversion("/home/kmodi/.emacs.d/elpa_27/elfeed-20180219.1340/elfeed-link.el" "/home/kmodi/.emacs.d/elpa_27/elfeed-20180219.1340/elfeed-link.el" nil t)
  elfeed-link-store-link()
  org-store-link(nil)
  org-babel-tangle-single-block(1)
  org-babel-tangle-collect-blocks(nil nil)
  org-babel-tangle(nil)
  funcall-interactively(org-babel-tangle nil)
  call-interactively(org-babel-tangle nil nil)
  command-execute(org-babel-tangle)
```

Surprisingly though, `(require 'org)` does not cause this error, but running Org tangle `C-c C-v t` always fails.

Emacs version:

> Emacs version: GNU Emacs 27.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 2.24.23)
 of 2018-02-21, built using commit d599dce1353ce59d134fcff21cde02c70025253d.

Org version:

> Org mode version 9.1.6 (release_9.1.6-493-g79b36b @ /home/kmodi/usr_local/apps/6/emacs/master/share/emacs/site-lisp/org/)

**Comment by kaushalmodi** [comment]
I have verified that this fixes the problem:

```elisp
(eval-after-load 'org
  '(progn
     (if (version< (org-version) "9.0")
         (with-no-warnings
           (org-add-link-type "elfeed" #'elfeed-link-open)
           (add-hook 'org-store-link-functions #'elfeed-link-store-link))
       (with-no-warnings
         (org-link-set-parameters
          "elfeed"
          :follow #'elfeed-link-open
          :store #'elfeed-link-store-link)))))
```

I don't understand why funcall and lambda were needed, but above works. Also the autoload cookie doesn't seem to be needed.

**Comment by skeeto** [comment]
Thanks for reporting this. You've supplied be with a topic for a whole 
new article. Also, it looks like you're using Elfeed uncompiled, so you 
should try fix that. It will run a lot more smoothly, especially with 
some of the complicated macro expansions.

Your fix would work, but the quote means the expression wouldn't get 
compiled. This code is trivially short and only runs once, so there are 
no practical performance benefits for byte-compiling it. However, the 
compiler does static analysis that's good for catching mistakes ahead of 
time, so I want everything to be compiled if possible.

Unfortunately eval-after-load is a fundamentally flawed function that 
should have been given more thought before it was added to Emacs all 
those years ago. It's a perfect example of eval abuse. This function was 
dramatically improved in Emacs 25 _and_ replaced with the properly 
designed with-eval-after-load. Elfeed supports back to Emacs 24.3, so I 
can't use these.

The workaround for eval-after-load is to capture the code to be 
evaluated in a function, so that the s-expression handed to eval is just 
(funcall <function-object>). The damaged caused by eval is minimized. I 
did this using a backquote, allowing the code to be evaluated at load 
time (and therefore subject to the compiler), while also capturing it in 
an s-expression for the sake of the misguided eval in eval-after-load.

My mistake was assuming that function objects are self-evaluating, just 
like numbers, keywords, strings, and vectors — values that never need to 
be quoted. This is really only true for byte-compiled function objects, 
which is all I was thinking about.

An interpreted lambda expression under dynamic scope evaluates to a 
function object that _coincidentally_ has the same representation as the 
original function. That is, lambda expression evaluation is idempotent. 
This didn't need to be the case. It's just how the Emacs Lisp 
interpreter was implemented and, strictly speaking, it's an 
implementation detail that happens to be mostly compatible with 
byte-code objects being self-evaluating.

The following demonstrates that dynamic scope lambda expressions do 
_not_ self-evaluate, but are instead just idempotent:

    ;;; -*- lexical-binding: nil; -*-

    (let ((x '(lambda ())))
      (eq (eval x) (eval x)))
    ;; => nil

    (let ((x '(lambda ())))
      (equal (eval x) (eval x)))
    ;; => t

An interpreted lambda expression under lexical scope evaluates to a 
closure object. This object neither evaluates to itself, nor is it 
idempotent. It is an error to evaluate this object because it appears to 
be a function call to a function named "closure". Indeed, this is the 
error you saw. (Perhaps Emacs _should_ have a function named "closure" 
that makes this work? I don't know, that sounds kind of… impure to me, 
and using it covers up an error in logic.)

The proper solution is to quote the result of evaluating the lambda 
expression. This prevents the function object from itself being 
evaluated. That way we don't care if this kind of object is idempotent, 
self-evaluating, or neither. It always works.

**Comment by kaushalmodi** [comment]
> Also, it looks like you're using Elfeed uncompiled

I am surprised why that's the case; I did not do that deliberately.. had simply installed it via Melpa. But I just deleted and reinstalled elfeed and elfeed-link.el and all others had their byte-compiled versions too. *So it's a mystery to me why elfeed-link.el was sitting earlier only in its uncompiled form.*

> the compiler does static analysis that's good for catching mistakes ahead of time, so I want everything to be compiled if possible.

That's good to know, thanks!

Also thank you for taking time to explains the details. I honestly will need to reread this a few times to understand it completely as I don't understand the internals of byte compilation and closures, etc.
