### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by kaaninho** [skeeto/elfeed#276]
Hello,
I am trying to get elfeed working on Windows with Emacs, but I cant get it there.
Adding works ( the var 'elfeed-feeds' is ("https://stackoverflow.com/feeds/tag/clojure") ), but when I try to update, nothing happens and in the elfeed-log-frame I get this error

> [2018-05-17 18:20:00] [error]:  https://stackoverflow.com/feeds/tag/clojure: "(2) Failed to initialize."

curl is installed and I can download the feed manually via CMD.
The 'elfeed-use-curl' variable is also "t".

Can you help? Thank you!

**Comment by skeeto** [comment]
This is an issue with your curl installation — maybe a missing DLL or 
something like that. It exited with error code 2 and the "Failed to 
initialize" message comes from curl itself. Does it work if you try to 
run curl outside Emacs?

curl https://stackoverflow.com/feeds/tag/clojure

The first step is to make that work. If it does, figure out why it fails 
when Emacs calls it (e.g. due to a different environment). You'll need 
to fix/reinstall curl or search for a workaround with something like 
"curl failed to initialize".

**Comment by kaaninho** [comment]
> curl https://stackoverflow.com/feeds/tag/clojure
This works already. 

Hmm okay, I'll try to find something.

**Comment by skeeto** [comment]
To see what arguments Elfeed uses with curl on your system for that URL, 
you can evaluate this:

(elfeed-curl--args "https://stackoverflow.com/feeds/tag/clojure" nil)

That might help narrow down the issue.

**Comment by kaaninho** [comment]
Thank you!
I tried these 3 args, that are getting added:

> --compressed 
> --silent
> --location

When using "compressed" I get an error: 

> curl: option --compressed: the installed libcurl version doesn't support this

May that be the problem? Can I work around the compression?

**Comment by skeeto** [comment]
Elfeed now only uses --compressed if curl advertises support for it. 
Thanks for this bug report!

**Comment by kaaninho** [comment]
Thank you!
