### ISSUE TITLE
Adjust preferred date for entries?

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#280]
Hi Chris,

While looking at the code for that other issue, I noticed the code that gets the date for entries in Atom feeds:

```el
(defun elfeed-entries-from-atom
...
(date (or (xml-query* (published *) entry)
          (xml-query* (updated *) entry)
          (xml-query* (date *) entry)
          (xml-query* (modified *) entry) ; Atom 0.3
          (xml-query* (issued *) entry)))
...)
```
I wonder, should the order of those be changed to prefer the date that entries were updated or modified on?

I don't know about RSS feeds; looking in the functions, they only seem to have `pubDate` and `date`, so I guess RSS doesn't even support updating entries.

Thanks.

**Comment by skeeto** [comment]
While it seems like it could make more sense to used the "updated" date, 
in practice this makes for a confusing and unpleasant experience. For 
example, Firefox gets this wrong and it's really obvious. Look at the 
Atom feed for any YouTube channel:

https://www.youtube.com/feeds/videos.xml?channel_id=UCkRmQ_G_NbdbCQMpALg6UPg

In Firefox, the video "Emacs Rocks at WebRebels! Part 04" (currently) 
displays as February 22, 2018 when the video was actually published 
October 17, 2013. That's because it treats the "updated" date as the 
primary date rather than the "published" date.

YouTube aggressively advances the "updated" date for the tiniest 
metadata changes — perhaps even when someone "likes" the video? — which 
*is* essentially what this element was designed to communicate. I would 
find it incredibly irritating for entries to jump around in time within 
Elfeed every time I update feeds, so instead it prefers the stable 
"published" date which isn't supposed to change.

Regarding RSS: Yes, it's a total mess! It wasn't nearly as carefully 
designed as Atom, which was created specifically to address all the 
shortcomings in RSS. I've written about this:

http://nullprogram.com/blog/2013/09/23/

Also see:

https://www.xml.com/pub/a/2002/12/18/dive-into-xml.html

(That article is from 2002, and fortunately the situation is a lot 
better today since nearly everyone using RSS is using version 2.0.)

So the right answer for RSS isn't a matter of reading spec (pick one, 
since there are seven incompatible versions of it) and carefully 
following the intention for different elements. It's more heuristic, 
using whatever interpretation happens to work best with existing feeds.

**Comment by alphapapa** [comment]
Thanks, Chris, for your patient explanations. Keep up the great work.
