### ISSUE TITLE
Cannot connect with proxy set in curl's extra arguments

### ISSUE THREAD

**Issue by omidmnz** [skeeto/elfeed#281]
I need to set a proxy to use curl for many of my feeds. Without setting the extra argument, I can load other links. But after `(setq elfeed-curl-extra-arguments '("-x http://localhost:8123"))`, I get the following error for every feed immediately:
```
[2018-06-06 20:30:23] [error]: <link>: "(7) Failed to connect to host."
```

I have tried a socks5 proxy, and an http proxy. Both fail the same way. In each case, I have tried a cleaned output of `(elfeed-curl--args "<link>" (elfeed-curl--token))` with curl on my command line, and it works as expected.

**Comment by skeeto** [comment]
The "-x" and "http://localhost:8123" must be separate strings in the 
list. Otherwise they're passed as a single argument. This looks like 
nonsense to curl. Here's what that would look like in a shell:

curl "-x http://localhost:8123" HOST

Alternatively you could just remove the space in that string, since 
joining putting an option and its argument together in one command line 
argument is also permitted by curl:

curl -xhttp://localhost:8123 HOST

Unfortunately the error message you got is misleading since curl doesn't 
have separate error codes for "Failed to connect to host", "Failed to 
connect to proxy", and "Unsupported proxy scheme". They're all grouped 
under error code 7, so you end up with a generic "failed to connect" 
message.

**Comment by omidmnz** [comment]
This solves the problem. Works perfectly now.
Thanks.
