### ISSUE TITLE
Elfeed doesn't update all feeds

### ISSUE THREAD

**Issue by fturco** [skeeto/elfeed#294]
I think Elfeed doesn't update all feeds on my list. When I press the "G" key, Elfeed displays "X feeds pending..." where X is always significantly lower than my total number of feeds. My problem seems similar to issue #235 but in my case using curl doesn't fix the problem. On my system the `elfeed-use-curl` variable is set to `t`, and `curl` is available in my `PATH`. I use elfeed 20180829.1716 from Melpa. Emacs version: 26.1. GNU/Linux distribution: Gentoo.

**Comment by skeeto** [comment]
That's actually counting jobs/tasks rather than feeds. Different feeds 
from the same domain are grouped up, fetched, and parsed as a single 
task (e.g. using a single TCP connection). So I should probably change 
the wording.

I see the same behavior since I have a bunch of YouTube channels in my 
feeds list, and so they're all counted as just a single feed for the 
heading counter.

**Comment by fturco** [comment]
I feel relieved it's not actually a bug in Elfeed and that all my feeds are actually being updated. Thank you for the information!

By the way, I would change to wording to something like "X jobs pending" instead of "X feeds pending".
