### ISSUE TITLE
Allow fetching from local files (file:// "protocol")

### ISSUE THREAD

**Issue by Quintus** [skeeto/elfeed#300]
Hi,

feature request: allow fetching from `file://` URLs. I have a script that scrapes websites that don't have feeds and builds Atom feeds from them that are output to a temporary directory. elfeed fails to fetch such feeds with an error message:

~~~~
Error running timer ‘elfeed-curl--call-callback’: (wrong-type-argument number-or-marker-p nil)
~~~~

`curl` itself does support fetching via `file://` (I tested it on the commandline). Currently, I work around the problem by using a web server on `localhost`, but that's just awkward.

**Comment by skeeto** [comment]
Yeah, in theory it could work with curl, too, since it understands the 
file protocol. The error is because curl doesn't, of course, produce an 
HTTP header in its response (-D option). Elfeed is trying to parse a 
non-existent header and getting stuck.

So Elfeed would need to examine the URL protocol to decide whether or 
not to try to parse an HTTP header. Or, if it's simpler, stuff a fake, 
empty header into the buffer just before parsing it.
