### ISSUE TITLE
Allow multiple, named *elfeed-entry-<NAME>* buffers

### ISSUE THREAD

**Issue by Ambrevar** [skeeto/elfeed#307]
`elfeed-show-entry` allows displaying only one buffer at a time.
It would be nice to automatically create one buffer per entry, so that we can display several entries at the same time.

```elisp
(defcustom elfeed-show-unique-buffers t)

(defun elfeed-show-entry (entry)
  "Display ENTRY in the current buffer."
  (let ((buff (get-buffer-create (if elfeed-show-unique-buffers
                                     (format "*elfeed-entry-<%s>*"
                                             (elfeed-entry-title entry))
                                   "*elfeed-entry*"))))
    (with-current-buffer buff
      (elfeed-show-mode)
      (setq elfeed-show-entry entry)
      (elfeed-show-refresh))
    (funcall elfeed-show-entry-switch buff)))
```

Thoughts?

**Comment by skeeto** [comment]
The original purpose was to keep it simple so that Elfeed didn't create 
tons of garbage buffers. Since your change makes it optional, I'll 
accept that as a PR with two caveats:

* Finish filling out that defcustom (docstring, group, type, etc.).

* I'm not entirely convinced the raw entry title is the most appropriate 
way to uniquify buffer names, but nothing much better comes to mind at 
the moment. Sometimes two different entries have the same time — or they 
even have no title at all. While the following is completely unique, 
it's not useful to someone looking at the buffer list:

(sha1 (prin1-to-string (elfeed-entry-id entry)))

Giving my own Elfeed entry listing a look, it seems the entry title will 
be sufficient at least 99% of the time. This can always be changed 
later.

**Comment by Ambrevar** [comment]
I've appended the date to the title, that should reduce the number of collisions to a minimum.
We could also append a shortened sha1 if you like.
