### ISSUE TITLE
How can I interrupt feed update when it's stuck (without restarting emacs)?

### ISSUE THREAD

**Issue by brabalan** [skeeto/elfeed#33]
When I update my feeds, the updating sometimes gets stuck (nothing happens after a while, and the status text remains at "89 feeds pending, 1 in process ...").

I've tried doing C-g, q, or killing the buffer, but I found the only way to quit the update process is to restart emacs. Is there a better way?

**Comment by shrysr** [comment]
Hey guys, I'd be glad to know :-
1.  Are there any further updates to this issue? Elfeeds still hangs up emacs regularly for me..
2. if emacs is completely stuck, while updating elfeed :  how is the elfeed-unjam command applied ?

**Comment by skeeto** [comment]
When it completely locks up it's usually a DNS issue. Currently Emacs
resolves DNS synchronously, so if you're talking to a crappy DNS server
(i.e. your corporate DNS server at work) you'll experience frequent
lockups. (On Windows it's even worse, since TCP connections are also
established synchronously.) Emacs should be switching to asynchronous
DNS resolution in a future release, which will hopefully fix this
problem:

https://lists.gnu.org/archive/html/emacs-devel/2016-01/msg01348.html

You should be able to use C-g to break out, though in my experience it
can be slow to respond. Using C-g while url-queue is active will usually
confuse the url-queue queue, which is where elfeed-unjam comes into play
(resets url-queue when it gets itself into a bad state).

**Comment by shrysr** [comment]
Christopher, thanks for your reply. Should using emacs from within Linux 
on virtualbox in windows make a difference, i.e enable emacs to 
establish TCP connections asynchronously ?

I have just setup emacs, compiling from source in Lubuntu. The fonts, 
theme and the entire feel of orgmode in emacs is quite different, not to 
mention several 'bugs' like table mis-alignments have vanished !

NOte: As such, it does seem to make a difference. I tried to load an 
opml file into elfeed on my emacs in windows, several times, and it 
Never loaded. HOwever, it happened perfectly the very first time on Lubuntu.
