### ISSUE TITLE
No way to use regex filter with spaces

### ISSUE THREAD

**Issue by cowile** [skeeto/elfeed#336]
Something that has annoyed me often about the filter syntax is the lack of a way to include spaces in the regular expression. Spaces occur in practically all article titles.

This is not terrible issue and the same results can usually be had with some more creative expressions, but this is annoying and not the right thing. Looking at the code, `elfeed-search-parse-filter` does a simple `split-string` using the default whitespace, making this impossible.

The right thing is a smarter parse function that can recognize escaped characters or quoting, but changing the split character to something less common in English text is probably acceptable. Commas or semicolons are both commonly used as separators, but less common in text than spaces.

**Comment by skeeto** [comment]
Yup, right now you have to use "\s-" or similar to match spaces in your 
filters. It's something I'd like to improve, but, in my own experience, 
it's not something I commonly need. That's why I didn't even notice it 
was broken in feed filters (=) until b3fc253. Unlike tag filters, regexp 
filters are already a rough-grained, so being a little rougher hasn't 
mattered much to me.

I've also never found a satisfying solution for quoting/escaping. I like 
and prefer spaces for separating filter elements, and I think it's a 
more valuable use of space than supporting spaces directly in regexp 
filters. Escaping leads to the same awkward problem Emacs Lisp has with 
regular expressions in strings: double escaping leading to backslash 
explosions.

Quoting also requires escaping, but it could be nicer by, say, using 
CSV-style escaping where quotes escape quotes. For example:

@1-month-ago "The ""I"" In Team"

Or:

@1-month-ago ="Joseph ""Buster"" Keaton"

For the sake of live filters, the filter parser would implicitly append 
missing quotes at the end of the filter. As you pointed out, this could 
be entirely implemented in a smarter replacement for split-string.

**Comment by cowile** [comment]
I agree with you.

Probably the best solution for me is to get used to typing `\W` for non-word characters or `[[:space:]]` if I truly need to specify whitespace.
