### ISSUE TITLE
End of file during parsing of elfeed-search.el

### ISSUE THREAD

**Issue by bertschneider** [skeeto/elfeed#352]
First off this is my first attempt at using `elfeed` so perhaps I am doing something completely wrong. So sorry in advance if that's the case. 

When I try to start `elfeed` I get the following parsing error in `elfeed-search.el`:

    End of file during parsing: ~/.emacs.d/elpa/elfeed-20191227.426/elfeed-search.el

Trying to byte compile gives the somewhat more meaningful error:

    elfeed-search.el:13:1:Error: End of file during parsing: ~/.emacs.d/elpa/elfeed-20191227.426/elfeed-search.el

The mentioned line is `(require 'elfeed)`, but that should be present, shouldn't it?

I use `use-package` to download and bind elfeed. 

    (use-package elfeed
      :ensure t
      :bind ("C-x W" . elfeed))

The version is `GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29`. Furthermore I deleted the `elpa` folder and redownloaded  and recompiled all used packages but without any change.

Am I doing something obviously wrong and if not how could I try to debug this error?

**Comment by skeeto** [comment]
This looks like an issue with your local system rather than anything in 
Elfeed. That particular version of the package as hosted by MELPA looks 
fine. Is the package.el-installed elfeed-search.el actually truncated at 
line 13? If the contents don't exactly match the contents of the file in 
this repository, then that's the place to start searching for problems. 
It should be identical.

Elfeed has no dependencies other than Emacs itself, so it's easy to 
bypass MELPA and package.el for testing. When you clone this repository 
and then run "make check" it should pass all the tests without errors. 
With Emacs 26 there should be no compiler warnings either. When you run 
"make virtual" you will get an Emacs instance running Elfeed isolated 
from your configuration.

**Comment by bertschneider** [comment]
Sorry for the late reply. 

The local `elfeed-search.el` file is the same as in the repo and not truncated at line 13. It seems like a different evaluation order so that `(require 'elfeed)` can not be resolved. 

`make check` and `make virtual` works locally so it is probably a problem with my emacs configuration. I will investigate further. 

Thank you for your help and the great project! :+1:
