### ISSUE TITLE
question: reset "last-updated"-date possible?

### ISSUE THREAD

**Issue by herrsimon** [skeeto/elfeed#353]
Hello,

I'm monitoring a feed which is generated by an api call which includes a ``max-items`` paramete in the feed url. As there only appear about 20 new items a day and I usually check the feed daily, I have set ``max-items=100``. Over the holidays however, I did not check the feed and before updating it today with elfeed I forgot to adjust the ``max-items`` parameter accordingly. So now of the approximately 500 new items, only the last 100 were fetched and when updating the feed again after setting ``max-items=1000``, the missing items are not showing up. I guess this is because elfeed internally stores a last-updated date and only fetches items which are newer

Is there an easy possibility to get the missing older items into elfeed? 

Thanks in advance!

**Comment by alphapapa** [comment]
I don't see a way to do so interactively, so you could probably do it with some Elisp something like:
```el
(setf (elfeed-meta feed :last-modified) nil
      (elfeed-meta feed :etag) nil)
```
With `feed` bound to the feed's entry as returned by `(elfeed-db-get-feed url)`.  See `elfeed-update-feed`.

(You should probably exit Emacs and backup your feed database first, of course.)

**Comment by herrsimon** [comment]
worked like a charm, thanks a lot!

**Comment by alphapapa** [comment]
@skeeto Would it be helpful to have an interactive way to force a feed to update?

**Comment by skeeto** [comment]
Thanks for answering this, alphapapa!

If the issue came up frequently then perhaps there ought to be a 
convenient user interface for doing this. Since this is essentially a 
server misconfiguration — the content has changed, but the server is 
responding with 304 Not Modified to old ETags — it shouldn't really be a 
common issue. Even when it happens, it's likely only temporary, lasting 
only until the next update.
