### ISSUE TITLE
Memory Consumption issues

### ISSUE THREAD

**Issue by SidharthArya** [skeeto/elfeed#357]
I  have been using elfeed to track about 900 feeds, and i have been having very high memory consumption when i am using elfeed. Without elfeed, emacs doesn't consume as much. My best guess is my database has become too large now and that is why it's consuming so much memory. 

Would it be possible to have a variable which would specify the number of days the days before the current day, database should load into memory, to reduce unecessary memory 
consumpton?

I am not really sure about how elfeed does what it does, so maybe archiving the read articles which were read before number of days since current maybe helpful. And maybe a variable which could tell whether to include archives or not?

Also since, i am suggesting archiving, it maybe necessary to not add the already archived articles again when updating?

**Comment by skeeto** [comment]
900 feeds! How high of memory consumption are you seeing specifically? 
Elfeed can only scale so far, and, depending on how often these feeds 
update, you unfortunately might be pushing beyond that limit. The index 
is an AVL tree of entry metadata for every entry ever seen, and it is 
kept entirely in memory. The feed content is not, so the size of the 
content itself generally doesn't matter. Without a proper database (i.e. 
SQLite), that's about the best I can do with Elfeed.

To get a picture of the scale, I'm curious about the number of entries 
you have, and the total size of your index. For the former, evaluate 
(elfeed-db-size), and for the latter make sure the database is saved 
(elfeed-db-save, elfeed-search-quit-window, etc.), then look at the size 
of your .elfeed/index file. Currently mine is 52k and 26MB, which is 
quite comfortable, but if it was an order of magnitude larger I could 
see this starting to be unwieldy.

I've avoided adding features to remove entries from the database because 
it's not so straightforward. This includes "archiving" entries. If 
entries are simply removed from the index, but they still exist in the 
feed, they'll just get picked up again as "new" on the next fetch. So to 
do it properly, Elfeed must actively remember deleted entries, at which 
point you're not actually saving anything. You'd have to be sure they 
never appeared in the feed again, which depends a lot on the feed.

Thinking about it more, I came up with this: Suppose Elfeed keeps track 
of the last time an entry was seen (:last-seen meta slot?). Then you 
could fairly confidently purge entries that haven't been observed in a 
feed for some period of time.

**Comment by SidharthArya** [comment]
(elfeed-db-size) evaluates to 39627. Actually i am using about 545 of the feeds right now evaluated with (length elfeed-feeds). I have about 4 GiB of memory and emacs is using about 75% of it, so about 3 GiB. I like the idea of last-seen meta slot very much. 

Also if the issue with archiving is that it may fetch the feeds which have been archive, it may be possible to circumvent this issue by using the date at which a particular news item was published. All the feed items which were published before a particular date will be ignored. The issue which will remain is when a new feed is added we may want to add all feed  So if the elfeed-feeds variable be stored in a different file. When a new feed item is added, the two lists (elfeed-feeds and the one stored in file) can be compared and only for the newer item all feeds will be fetched. Maybe i can work on this ?

**Comment by skeeto** [comment]
How big is your .elfeed/index file? That's roughly how much memory 
Elfeed is using. To consume 3GB of RAM, each of your entries would be 
more than 75kB on average. Typically they're under 400 bytes, depending 
mostly on the length of the title. So the problem is something other 
than a large number of feeds.

If you close Emacs, clone this repository, then run "make virtual", it 
will start a standard-config Emacs with your index loaded (in isolation, 
so changes will not persist). Does this still consume 3GB of RAM?

**Comment by skeeto** [comment]
Oh, and "M-x elfeed" after "make virtual" so that it actually loads your 
Elfeed database.

**Comment by SidharthArya** [comment]
I see. My elfeed/index file is just 24.8MB. And "make virtual" does seem to work perfectly well.  It must be something in my config that's a problem here. Thank you so much for your help on this. So I am closing this now since I am experiencing no issues at all with the isolated instance.

**Comment by SidharthArya** [comment]
It was a garbage collection issue, sorry to even bother you with this.

**Comment by skeeto** [comment]
Could you elaborate on what you discover (gc-cons-threshold issue, 
etc.)? You probably won't be the only person to have this problem, and 
someone with this problem or similar may come across this thread in the 
future.

**Comment by SidharthArya** [comment]
Yes  I can. I had gc-cons-threshold set too high during startup and i did not reduce it back to a smaller value after init. So all that garbage was remaining in my memory . So even without elfeed running emacs instance will consume about 5-7% of RAM which is still high but not very bothersome. But when I started elfeed, I will see an immediate spike in RAM usage, which was where i got the idea that this was an elfeed issue, which it was not. 
So I didn't set the gc-cons-threshold variable during startup and this issue was resolved. In my case the default value of gc-cons-threshold seems  to work fine. 
I had also set gc-cons-percentage to 0.6 or so, which i removed after realizing this.
My gc-cons-threshold value is 800000 and gc-cons-percentage is 0.1 currently.
