### ISSUE TITLE
elfeed-show-entry-switch should be a defcustom

### ISSUE THREAD

**Issue by alphapapa** [skeeto/elfeed#361]
I think `elfeed-show-entry-switch` should be a `defcustom` so that it would be more discoverable and to indicate that it is intended to be customized.  :)

**Comment by alphapapa** [comment]
Specifically, how about this:
```el
(defcustom elfeed-show-entry-switch #'pop-to-buffer
  "Function to call to display and switch to the feed entry buffer.
Defaults to `switch-to-buffer'."
  :type '(choice (function-item switch-to-buffer)
                 (function-item pop-to-buffer)
                 function))
```
I think `pop-to-buffer` is a better default now, because it seems to respect existing window layouts better.  `switch-to-buffer` seems to always open a new window when I wanted it to use the one next to the search buffer.

**Comment by skeeto** [comment]
Yup, you're exactly right on the defcustom. I normally don't think of it 
since I never use the customization system myself. I'm happy to accept a 
PR with your proposed change.

I don't like the behavior of pop-to-buffer for showing entries. If I 
have a single window showing the search buffer, and I hit "RET" on an 
entry, it splits the frame and opens the entry in the new window. That's 
not so bad, but when I hit "q" to dismiss the entry it leaves behind the 
extra window, which I really don't like.

(The "make virtual" target is a good way to try this out using a default 
configuration Emacs, and it's a reasonable representation of how a new 
user would experience it.)

With switch-to-buffer, the entire window changes to the entry, which I 
prefer, and, more importantly, when I hit "q" I go right back to the 
search buffer just the way I was. Though I admit I tend to avoid any 
window management, even outside of Emacs, and I like having a single 
view at a time. For example, I dislike the sidebar extension in 
(Neo)Mutt, and I actively avoid Vim splits.

**Comment by alphapapa** [comment]
Ok, I sent a PR that converts the show-entry function `defvar`s to `defcustoms`, and it doesn't change the default behavior.  Thanks.
