### ISSUE TITLE
Handling HTML in feed titles

### ISSUE THREAD

**Issue by ahacop** [skeeto/elfeed#365]
First, thanks very much for the great software.

A handful of the feeds that I follow use HTML tags and entities in the title of an article. In order to decode the HTML, in my config I've added a decoding function and modified a couple of elfeed functions (`elfeed-search-print-entry--default` and `elfeed-show-refresh--mail-style`) to make use of the decoding function. I've never written elisp, so there is probably a better way to do this. In any case, maybe someone out there will find this information useful.

```elisp
(defun decode-entities/libxml (html)
   (unless (fboundp 'libxml-parse-html-region)
     (error "This function requires Emacs to be compiled with libxml2"))
   (with-temp-buffer
     (insert html)
     (let* ((document (libxml-parse-html-region (point-min) (point-max)))
            (decoded-string (dom-texts document)))
       decoded-string)))
```

**Comment by skeeto** [comment]
HTML in titles is one place where Elfeed falls short. However, in my 
observations, most instances of feeds using HTML in titles is invalid or 
unambiguous, so adding this feature wouldn't help. For example, RSS 
never allows HTML in titles, though many feeds try anyway.

Atom does allow it if the type attribute is set to "html or "xhtml", and 
Elfeed could check for this attribute and process the title accordingly. 
As you noticed in your code, this is complicated by the fact that no 
HTML parser may be available, and so Elfeed may not always be able to 
parse it. So I'd prefer to just use a simple routine that reliably 
decodes entities and strips all HTML tags, since titles can't be 
meaningfully styled in Elfeed's interface anyway.

The proper place to do this would be in elfeed-entries-from-atom.

**Comment by ahacop** [comment]
Thanks for the pointer to `elfeed-entries-from-atom`.

Here's an implementation that neither requires libxml nor creates thousands of dom representations and temporary buffers. On the other hand, my regexs are probably incomplete or just plain wrong. 😄 

```elisp
(defun ah/decode-html/compose (&rest funs)
  "Return function composed of FUNS. Source: https://nullprogram.com/blog/2010/11/15/"
  (lexical-let ((lex-funs funs))
    (lambda (&rest args)
      (reduce 'funcall (butlast lex-funs)
              :from-end t
              :initial-value (apply (car (last lex-funs)) args)))))

(defun ah/decode-html/entity->character (entity)
  (gethash entity ah/decode-html/entities-hash entity))

(defun ah/decode-html/strip-html-tags (html)
  (replace-regexp-in-string "\\(<[^>]+>\\)" "" html))

(defun ah/decode-html/decode-html-entities (html)
  (replace-regexp-in-string "\\(&[^;]+;\\)" 'ah/decode-html/entity->character html))

(defun ah/decode-html (html)
  (funcall (ah/decode-html/compose 'ah/decode-html/decode-html-entities 'ah/decode-html/strip-html-tags) html))
```

`entities-hash` is a hash table with a few hundred entity->character mappings.

**Comment by ahacop** [comment]
Would you consider accepting a PR for a fix that strips tags and decodes entities on titles with the html/xhtml type?
