### ISSUE TITLE
Updated date in atom feeds

### ISSUE THREAD

**Issue by linwaytin** [skeeto/elfeed#393]
I try to use elfeed to fetch atom feeds from Arxiv.
I noticed that elfeed does not show feeds with updated dates.
More precisely, it tends to show the initial version rather than the updated version.

When I switch the order of `(xml-query* (published *) entry)` and `(xml-query* (updated *) entry)` in `elfeed.el`, I can get the updated version.
Is it possible to add an option to choose the behavior?

Thank you.

**Comment by skeeto** [comment]
This is very intentional since some feeds, particularly YouTube, 
constantly update their entries such that their "updated" element is 
essentially just the fetch date. That's generally not very useful, so 
Elfeed tries to ignores it.

Unfortunately this is not currently configurable. You may be able to 
address this using a custom elfeed-new-entry-parse-hook function that 
plucks the date you want from the XML and sets that as the entry date.

**Comment by linwaytin** [comment]
Ok I see.
Thanks for your explanation.
