### ISSUE TITLE
elfeed only showing only15-20 enteries for each feed  

### ISSUE THREAD

**Issue by ashish-patwal** [skeeto/elfeed#405]
i am trying to get all the feeds from elfeed . But it turns out that it shows enteries/posts till 3 months old , while if i see on the site there are more posts dating back months , years and so on .
This problem seems to be with every feed i have on my config file .

Is there any default function / value i am missing that i have to modify in  my config file ?

Please help .

**Comment by skeeto** [comment]
Either you have a filter in place limiting the listing to the past three 
months ("@3-months-old"), or the feed itself only goes back that far. 
It's common for feeds to list fewer posts than available on the site 
itself, particularly since feeds are primarily intended for updates 
(i.e. recent posts).

**Comment by ashish-patwal** [comment]
thank you i seem to have understood the concept behind it . It seems elfeed only writes enteries to the database up to a certain time stamp or certain interval . So if you're using it for a year you'll have more enteries written to the database than someone who just started using elfeed .
But i'll certainly look to find a solution to change the amount of enteries that elfeed writes to the database .
