### ISSUE TITLE
Can you set new tag?

### ISSUE THREAD

**Issue by Lenin1917** [skeeto/elfeed#412]
some distro like GNU Guix distribute only release of packages. In light of recent events (add gopher support) it would be nice to release new version, isn't it?

**Comment by skeeto** [comment]
I've just tagged 3.4.0. I hadn't realized it had been over a year since 
the last tag. I kept intending to do it the past year or so. A couple 
changes would trickle in, so I'd decide to wait awhile to shake out any 
problems found by bleeding edge users on MELPA. Then a month later 
something new, so I put it off again.

**Comment by Lenin1917** [comment]
thanks!
