### ISSUE TITLE
How to get the details of current active jobs?

### ISSUE THREAD

**Issue by snowman** [skeeto/elfeed#413]
Currently, due to network issues, it has `0 jobs pending, 1 active...` on the header-line. 

After 5 minutes, finally, it shows the failed result in `*elfeed-log*`. 

But how to check the status of elfeed manually? something like `M-x describe-variable RET` 🤔, and possibly run a function to cancel it.

**Comment by skeeto** [comment]
First, make sure Elfeed is using curl. The variable elfeed-use-curl will 
be set to t automatically if Elfeed can find the curl program. Otherwise 
it falls back on Emacs' url-retrieve which is prone to misbehavior much 
like you're describing. If you must, the elfeed-unjam function exists to 
hard reset the url-retrieve queue when it gets itself into a bad state.

With the curl backend you shouldn't be experiencing hangs like that since 
curl will timeout lingering requests. (Though on very rare occasions this 
doesn't work right, but it's so unusual that I haven't been able to debug 
it.)

Another possibility is that the header line isn't updating when it should, 
and there's nothing actually pending. I revisited this a few months ago, 
but I might have still missed something. (One issue has been that Emacs 
doesn't consider erase-buffer as a modification for buffer-modified-tick.)

You can access those counts directly with the elfeed-queue-count-total and 
elfeed-queue-count-active functions.

**Comment by snowman** [comment]
Thanks for the long and detailed comment, the variable `elfeed-use-curl` is `t` in my case.

Today when I run `elfeed` again, there are no pending jobs. 

So the best way to avoid this from happening is to ensure you have the good QoS. :sweat_smile: :thinking: 

Note for busy man:
- run `M-x elfeed-unjam RET` to cancel the queue.
- run `C-h v elfeed-curl-queue` to check for list of pending curl requests.
