### ISSUE TITLE
Not showing the information about a video/link to it when using Youtube XML

### ISSUE THREAD

**Issue by ludblom** [skeeto/elfeed#417]
When adding a channels XML file to my feed and get a notice that a new video have been uploaded I just get `(empty)` in the `*elfeed-entry*`.

Reproduction of this problem should just be to add a channel, like [https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA](https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA), update and select an entry.

**Comment by ludblom** [comment]
Was a problem with an extension called `elfeed-goodies`, not elfeed itself

**Comment by skeeto** [comment]
Just to add a general note about this: YouTube used to include entry 
summary / content in their Atom feeds with the video description, but at 
some point they stopped using these (required!) Atom elements and switched 
to the defunct Yahoo! Media RSS XML namespace. The result is no feed 
summary unless the client supports Media RSS extensions… in an Atom feed. 
Why did they do this? Probably just some people at Google didn't know any 
better and didn't bother to check if their changes were actually valid and 
correct.

Fortunately this doesn't really matter since the actual entry is the video 
itself, not the description, and YouTube's mistake saves Elfeed time 
processing an unneeded, and usually unwanted, video description.
