### ISSUE TITLE
Puzzling wrong-type-argument stringp error

### ISSUE THREAD

**Issue by brittAnderson** [skeeto/elfeed#444]
I have some feeds that show up in the log with an error of the above type. If I just type the feed in the address box of firefox all is fine. If I run curl on the command line it gets the text. If I run `(cl-every #'stringp (elfeed-feed-list)` it returns true (as does a stringp on one of the offending urls). Any ideas how to figure this out?  It also does not seem consistent, failing at times, but not other. 

A couple of examples: 
[2021-09-28 10:50:58] [error]: https://www.lemonde.fr/rss/une.xml: (wrong-type-argument stringp nil)
[2021-09-28 10:38:58] [error]: https://www.reddit.com/r/haskell/.rss: (wrong-type-argument stringp nil) - but other reddit feeds worked fine. 

Using linux (arch) and emacs 27.2 elfeed 3.4.1

**Comment by alphapapa** [comment]
You'll need to post a full backtrace in order to know where the error occurs.

**Comment by brittAnderson** [comment]
A little more detail please. The "error" is listed in the *elfeed.log*, but elfeed continues to execute. Toggling on the debugger and running "G" from in elfeed updates the feed, but if I look in the log it shows the errors and I can see certain feeds are not updated. I can run "G" again, and maybe this time they do update. What do you want a backtrace of?

**Comment by alphapapa** [comment]
All I know is that `(wrong-type-argument stringp nil)` is an Elisp error, and without the backtrace showing what caused it, it would be hard to know what caused it.  I guess Elfeed is using a `condition-case` somewhere to handle the error without aborting the update process.  Maybe there's an option to disable that and allow the error to be fully signaled.

**Comment by skeeto** [comment]
Thank you for sharing as much detail as was available (versions, URLs).

That's correct that the backtrace is being swallowed by a condition-case 
in elfeed-update-feed, which elfeed-handle-parse-error turns into this log 
message. The quick-and-dirty way to get a backtrace would be to print one 
from the error handler hook (to *Messages*):

(push (lambda (_ _) (backtrace)) elfeed-parse-error-hooks)

However, I don't think a backtrace will be useful here anyway. The server 
is probably sending you something weird on occasion, and Elfeed isn't 
being graceful about handling it. These feeds work fine on my end, so it 
seems I'm not getting the same response. You could save off what Elfeed 
sees by way of the same hook, different hook function:

(push (lambda (_ _) (write-file "/tmp/debug")) elfeed-parse-error-hooks)

You're not seeing "Unknown feed type." in your log, so whatever is 
arriving looks feed-like enough to pass XML parsing and classification. 
With that hook, the contents of /tmp/debug might be interesting.

Another option is to run curl exactly the same way Elfeed does and see if 
it ever gets something weird. Evaluating this will return the list of curl 
arguments used for a given URL:

(elfeed-curl--args "https://www.lemonde.fr/rss/une.xml" nil)

Another possibility is interference from your particular Emacs config, and 
perhaps Elfeed is relying on a default where it shouldn't. Though I'm 
skeptical of this since you said it's not consistent. You can test in an 
isolated, clean environment by cloning this repository and running "make 
virtual", use M-x elfeed-add-feed, and see if you can reproduce. (It will 
use a temporary copy of your Elfeed database, and nothing will be written 
back out to the original.)

**Comment by brittAnderson** [comment]
Thank you for the detailed suggestions. The intermittency makes debugging this a challenge. I will work on this as time permits. I guess since a solution remains uncertain I will close and add a comment or request to re-open if I ever get anything concrete to share. Thanks for the software.
