### ISSUE TITLE
Feature: async elfeed

### ISSUE THREAD

**Issue by csantosb** [skeeto/elfeed#66]
Wouldn't it be possible to implement async updating of feeds using the [emacs-async library](https://github.com/jwiegley/emacs-async) ?

There is a similar use of it for 'paradox' as explained [here](http://endlessparentheses.com/asynchronous-package-upgrades-with-paradox.html)

**Comment by skeeto** [comment]
Currently fetching feeds is asynchronous: the interpreter thread is not
blocked while the XML is downloading. However, parsing the XML is
synchronous, and, since that's so slow, it's probably what causes the
perceptible drop in responsiveness during feed updates. If an async
Emacs subprocess fetched and parsed the XML, returning feed and entry
structs to the main Emacs process, I bet it would feel a lot smoother.

Originally I was hoping to resolve this with a better database (e.g.
SQLite) -- the subprocess would just insert its results directly in the
database, which would then be visible to the main process -- so I hadn't
investigated alternatives, but at this point, to be honest, the database
implementation isn't changing anytime soon. I'll take a look at using
emacs-async.

Why did you close the issue, though? Change of mind?

**Comment by csantosb** [comment]
Some time ago, refreshing feeds blocked emacs, this is why I open an issue as I thought it might be
a good idea using the paradox approach; then, I realized this is not the case anymore. Anyway, as
you say, there is maybe a chance to improve the usability by going to emacs-async.

**Comment by kototama** [comment]
Can we reopen this issue? I like elfeed very much but I'm considering finding another solution because it takes too much time to fetch ~16 feeds.

**Comment by skeeto** [comment]
@kototama Sure, this is sort of a long-term goal. Are you on Windows? It's unusual to have trouble with just 16 feeds. I've been following 120-150 feeds for 2.5 years now without difficulty (which is primarily why I haven't implemented async fetching). Some people have reported following a few hundred.

**Comment by kmicu** [comment]
FYI: Nowadays, I follow ≈2500 feeds with Elfeed (yey, ヽ(*＾▽＾)／ 🎉), but I use a separate Emacs instance to operate it; that way, fetching process does not interrupt my regular Emacs workflow.

**Comment by kototama** [comment]
What is Windows? More seriously no, I'm using it on Linux with `Emacs 24.5.1`. 

Now I see in the log that I have some "Queue timeout exceeded" even if the feed exists. I'll open a separate issue.

**Comment by emacswatcher** [comment]
Elfeed updates routinely cause timeout chaos for me.

**Comment by skeeto** [comment]
@emacswatcher Make sure you're using curl rather than falling back on 
the url-retrieve backend. If curl is in your PATH, elfeed-url-curl will 
be non-nil automatically, indicating it's probably set up correctly. If 
using curl still isn't enough, call elfeed-set-max-connections to reduce 
the number of concurrent connections. This may be necessary if you're 
using a very slow computer (e.g. a Raspberry Pi) or if you're on a very 
constrained network connection.

See also: http://nullprogram.com/blog/2016/06/16/

**Comment by skeeto** [comment]
Closing since this should be fixed by the switch to the curl backend: [Elfeed, cURL, and You](https://nullprogram.com/blog/2016/06/16/).
