### ISSUE TITLE
Is there a way to recreate the index?

### ISSUE THREAD

**Issue by Fuco1** [skeeto/elfeed#80]
I closed my emacs now, and after reopening elfeed only thinks I have ~450 things in my index.  When I count all the files in the `data` directory it comes to about 7000.  Is there some way I could recreate the index from scratch?  This means I'm going to loose the read/unread state, but having the search working is more important.

**Comment by skeeto** [comment]
You're seeing garbage in your .elfeed/ directory, that's all. Try
running M-x elfeed-db-compact to compact/optimize the database and
remove all those files. In the end you'll be left with 3 files no matter
how many entries you have. Elfeed tries to run the garbage collector
when Emacs closes to clean these up (e.g. elfeed-db-gc-safe in
kill-emacs-hook).

Why is this? Any time an entry's content changes between updates
(example: YouTube Atom feeds include a view count), it generates a new
"blob" under the data/ subdirectory, so a single entry may have
generated any number of individual files, but at most one is ever in use
per entry. Entries will share blobs if they have the exact same content.

**Comment by Fuco1** [comment]
Well I get about 40 feeds a day, for the past half a year that gives at least 7k items, which about matches the amount of files in the `data` directory.  The index file is now about 200kb, before it used to be 20 megabytes.  

Suppose I deleted the index file, is there a way to rebuild it?  Because I think this is the situation I'm at.

**Comment by skeeto** [comment]
Hmmm, I guess something about the index got corrupted at some point. All
of the significant data is stored in that index file, so the information
is already lost if you're seeing such a big reduction in size. For
comparison to your numbers, at 20k entries, the index on my current
machine is 12MB.

If you're going to delete the index and start over, make sure you have
Emacs closed when you do it. If not, it will restore the index from its
memory when it shuts down. You may as well delete the entire .elfeed/
directory if you go that route, because the data/ subdirectory won't be
relevant anymore either. Elfeed will start a fresh database next time
you use it.

**Comment by Fuco1** [comment]
Out of curiosity, do you version your index file somewhere?

It's not all that important information, but it's nice to have a way to go back and search for something when you need it.

**Comment by skeeto** [comment]
Elfeed doesn't do any sort of versioning of the index. It relies on
Emacs' use of fsync+rename (write-region-inhibit-fsync) to prevent data
loss in the index in the event of a system failure mid-write, so you
should be safe from that. Beyond that you'll have to make the index part
of your normal backups, since there's no way for Elfeed protect it from
a disk failure.

At one time there was a bug where Emacs would occasionally invoke a
database write with a non-nil print-level (some weird asynchronous
situation), which would corrupt the index, but this was fixed. I'm
currently not aware of any index corruption bugs. The Emacs' printer
does all the heavy work, so there's not much to break.

**Comment by Fuco1** [comment]
All right, thanks for all the answers.  I should have put it into my backup indeed, somehow it slipped my mind.

Thanks :)  I'm closing this as there's not much more to discuss.
