### ISSUE TITLE
[FEATURE] `elfeed-search-reset-filter`

### ISSUE THREAD

**Issue by jinnovation** [skeeto/elfeed#85]
After modifying filters in `elfeed-search`, it'd be useful to be able to instantly reset to the "default" filter configuration with a function named, say, `elfeed-search-reset-filter`, rather than having to manually call `elfeed-search-set-filter` and undo the modifications by hand.

**Comment by skeeto** [comment]
This is a pretty common custom binding. I have one set in my own configuration as `h` ("*h*ome").

~~~el
(define-key elfeed-search-mode-map (kbd "h")
  (lambda ()
    (interactive)
    (elfeed-search-set-filter (default-value 'elfeed-search-filter))))
~~~

There are a lot of little conveniences like this that could be bound to keys. Fortunately, since all of Emacs' extensibility is available, it's trivial for users to do for themselves. I bet it's equally hard to *discover* this sort of binding as it is to make/invent it yourself. So for stuff like this, I'd rather leave it up to user to bind it if they want it, and to choose how they bind it.

I suppose this could be simpler if `elfeed-search-set-filter` accepts nil to reset it, so I went ahead and made that change. The binding can now look like this.

~~~el
(define-key elfeed-search-mode-map (kbd "h")
  (lambda ()
    (interactive)
    (elfeed-search-set-filter nil)))
~~~

Or you can use `elfeed-expose` which is a version of `apply-partially` that returns interactive functions, so that they can be bound.

~~~el
(define-key elfeed-search-mode-map (kbd "h")
  (elfeed-expose #'elfeed-search-set-filter nil))
~~~
