### ISSUE TITLE
problem with some feeds

### ISSUE THREAD

**Issue by gour** [skeeto/elfeed#87]
I've problem with few feeds although they work in e.g. Sage:

```
Elfeed parse failed for http://www.harekrsna.com/sun/sun.rss: (error XML: (Well-Formed) Invalid character)
Elfeed parse failed for http://owncloud.org/blogfeed: Unknown feed type.
Elfeed parse failed for http://owncloud.org/blogfeed: (error Elfeed parse failed for http://owncloud.org/blogfeed: Unknown feed type.)
```

Any hint?

**Comment by skeeto** [comment]
The first is due to a misconfiguration of the server. The feed is served
encoded as UTF-16, BOM and all, but the Content-Type is only
"application/rss+xml" instead of "application/rss+xml; charset=utf-16".
This means url-retrieve decodes it as ISO-8859-1 (or maybe the default
encoding?) and Elfeed only gets garbage from url-retrieve. The HTTP spec
says to use ISO-8859-1 here, so this isn't really url-retrieve's fault.

Other clients are more accommodating to these sorts of misconfigurations
since it's so common. They'll switch to UTF-16 when detecting the BOM. I
could try to do the same by asking Emacs to re-decode the content using
its encoding detection mechanisms, but I can't actually figure out how
to do this without writing to a file. Does anyone know how to redecode a
buffer in place?

The second problem you're having is due to a bug in Emacs' url-retrieve.
I'm not able to figure out how or why, but it's making some sort of
invalid request to the server. Oddly, the server is also misconfigured
because it doesn't even send HTTP headers when this goes wrong! Try
evaluating this (notice the lack of HTTP headers in the response):

    (pop-to-buffer
     (url-retrieve-synchronously "http://owncloud.org/blogfeed"))

This bug exists in Emacs 24.5 (current stable release) but has been
fixed in the mainline Emacs. Since it's already been fixed for an
upcoming release, I'm not going to try to figure out a workaround. To
access this feed you'll either have to live on the bleeding edge or just
wait for Emacs 25 to be released.

Incidentally while researching that last one, I found a bug in
libxml-parse-xml-region that prevents it from parsing that particular
feed (so there are *two* Emacs' bugs in the way here!).

   (with-temp-buffer
     (insert "<foo><bar></bar></foo>")
     (libxml-parse-xml-region (point-min) (point-max)))
   ;; result: (top () (comment () " a ") (comment () " b "))

It can't correctly parse XML with two or more trailing comments!
Fortunately this has also been fixed in the mainline.

**Comment by gour** [comment]
@skeeto: Thanks a lot for your thorough analysis!! 

In regard to the first problematic feed, I'll contact them and I'll leave with those Emacs bugs until release of V25.

Recently I decided to settle much more on Emacs (mostly due to org-mode) and also switched from Gnus to mu4e so I really appreciate Elfeed which is, without any doubt, the best when it comes to RSS feeds, so FF's Sage is/was just temporary workaround after I left Claws-mail earlier.

**Comment by skeeto** [comment]
Closing since this old and outside of Elfeed's control.
