### ISSUE TITLE
get all unread from a specific feed

### ISSUE THREAD

**Issue by seblemaguer** [skeeto/elfeed#91]
Hello,

I would like to save all the unread entries from a specific feed to a list. For the moment, I manage to save all the entries by doing that : 

```lisp

(defvar unread-entries ())
(cl-loop for entry in (elfeed-feed-entries "url")
         do (push (elfeed-entry-title entry) unread-entries)
         )

(dolist (entry unread-entries)
    (message entry))
```

I know that I can use the tag to filter but I just if there is a more efficient solution

Thanks,
Sébastien

**Comment by skeeto** [comment]
Maybe you're looking for something like this?

```el
(defun insert-feed-unread-listing (feed-url)
  (interactive (list (completing-read "Feed: " (elfeed-feed-list) nil t)))
  (dolist (entry (elfeed-feed-entries feed-url))
    (when (member 'unread (elfeed-entry-tags entry))
      (insert (elfeed-entry-title entry))
      (newline))))
```

**Comment by seblemaguer** [comment]
Actually I was thinking about the fact that elfeed-feed-entries is reading all entries from the database instead of querying only the unread ones. If there a way to query only the unread ones outside the "elfeed-search" buffer ? If not, I will use your proposition thanks :)

**Comment by skeeto** [comment]
The database has three indexes, each keyed on one thing: feeds, entries,
and time. The first two are hash tables so that a specific feed or entry
can be found by its URL/ID in constant time. Being a hash table, they're
not ordered in any way (IDs don't have a meaningful ordering), so
traversal of these indexes isn't very useful.

The third index is a tree, ordered by time. The with-elfeed-db-visit
macro uses this index to efficiently visit entries from newest to
oldest. The index exists to support fast generation of the elfeed-search
buffer listing, especially so that the filter can be comfortably edited
on the fly.

Currently, there's no index over tags because there's never been a need
to find that information in a hurry. So to find all the entries having a
certain tag, or set of tags, you have to visit all entries across the
database (e.g. a table scan). You could traverse the entries index (hash
table) to do this, but the standard way to visit every entry is to use
with-elfeed-db-visit, even if you don't care about time ordering.

In your case, you want to find all the entries under a particular feed
that have a particular tag. The elfeed-feed-entries function does most
of the work, the full scan for entries belonging to that feed. After
that you're just operating on a list of structs (vectors) without any
more indexing into the database. Despite the scan, it *should* still be
pretty darn fast, especially when only run on occasion.

**Comment by seblemaguer** [comment]
Ok thanks a lot for the explanation :)
