### ISSUE TITLE
Slow insert of filter terms

### ISSUE THREAD

**Issue by Enrico68** [skeeto/elfeed#97]
Hello,

when I try to search, inserting the terms is  slow. Is this a normal behaviour ? I record and example. http://i.imgur.com/vc12KP2.gif

**Comment by Enrico68** [comment]
I saw now that the screencast uploaded on imgur is 3X faster :-). Sorry. Anyway take for grant what I wrote.

**Comment by skeeto** [comment]
The database is indexed by date because recent entries are nearly always
most important. Due to this index, date filters are by far the most
efficient. So when using the live filter, leave a date filter as one of
the components (ex. "@1-month-ago") to allow the filter to use the index
to bail out of the search early.

However, your issue did give me the new filter idea in the associated
commit. Filters can now have a maximum result count using #. The live
filter will use this implicitly to limit the results to the size of the
window to help make it more responsive. This won't help when there
aren't enough results to fill the window and the entire database is
scanned anyway.

The next responsiveness improvement would be to perform the filter
asynchronously or in batches on a timer. But I don't intend on
implementing something like this anytime soon. The date filter has been
Good Enough (TM) so far.

**Comment by Enrico68** [comment]
Christopher Wellons <notifications@github.com> writes:

> The database is indexed by date because recent entries are nearly always
> most important. Due to this index, date filters are by far the most
> efficient. So when using the live filter, leave a date filter as one of
> the components (ex. "@1-month-ago") to allow the filter to use the index
> to bail out of the search early.
>
> However, your issue did give me the new filter idea in the associated
> commit. Filters can now have a maximum result count using #. The live
> filter will use this implicitly to limit the results to the size of the
> window to help make it more responsive. This won't help when there
> aren't enough results to fill the window and the entire database is
> scanned anyway.
>
> The next responsiveness improvement would be to perform the filter
> asynchronously or in batches on a timer. But I don't intend on
> implementing something like this anytime soon. The date filter has been
> Good Enough (TM) so far.

Great!. Thanks.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/skeeto/elfeed/issues/97#issuecomment-122048482

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or

**Comment by Enrico68** [comment]
Now filtering is instantaneous. Thanks!
