### ISSUE TITLE
Wrong dates for http://andrew.gibiansky.com/feed.rss

### ISSUE THREAD

**Issue by deepfire** [skeeto/elfeed#99]
Adding `http://andrew.gibiansky.com/feed.rss` yields everything dated by today.

**Comment by skeeto** [comment]
That's because it uses an invalid format for dates. RSS 2.0 specifies
RFC 822 dates for pubDate (though this was likely a typo in the
specification and the authors *really* meant RFC 2822, which is what
everyone actually uses instead). That feed is using some free-form date
format, obvious to humans but not to computers.

Elfeed will try parsing pubDate as a few different formats, but the vast
majority of possible human language strings describing dates won't be
accepted. When it can't parse the date, it uses the timestamp that the
entry was first seen.

**Comment by deepfire** [comment]
@skeeto, understood.  Notifying the blog author about the issue..

**Comment by deepfire** [comment]
The author updated the RSS feed, so the dates conform with RFC 2822, but it's still wrongly dated -- can you take a look?

**Comment by skeeto** [comment]
It's still not in any standard date format, and, worse, it's even more
ambiguous than before. For example, "12 Jul 14" can easily be "July 12,
2014" or "July 14, 2012." Here are some example RFC 2822 dates:

Sat, 13 Mar 2010 11:29:05 -0800
Tue, 25 Aug 2015 18:35:33 +0000
Tue, 25 Aug 2015 14:35:44 -0400

Note the inclusion of time *and* timezone.

**Comment by gibiansky** [comment]
@skeeto I am basing my date format on [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) which has the following grammar for dates and times:
```
3.3. Date and Time Specification

   Date and time occur in several header fields.  This section specifies
   the syntax for a full date and time specification.  Though folding
   white space is permitted throughout the date-time specification, it
   is RECOMMENDED that a single space be used in each place that FWS
   appears (whether it is required or optional); some older
   implementations may not interpret other occurrences of folding white
   space correctly.

date-time       =       [ day-of-week "," ] date FWS time [CFWS]

day-of-week     =       ([FWS] day-name) / obs-day-of-week

day-name        =       "Mon" / "Tue" / "Wed" / "Thu" /
                        "Fri" / "Sat" / "Sun"

date            =       day month year

year            =       4*DIGIT / obs-year

month           =       (FWS month-name FWS) / obs-month

month-name      =       "Jan" / "Feb" / "Mar" / "Apr" /
                        "May" / "Jun" / "Jul" / "Aug" /
                        "Sep" / "Oct" / "Nov" / "Dec"

day             =       ([FWS] 1*2DIGIT) / obs-day

time            =       time-of-day FWS zone

time-of-day     =       hour ":" minute [ ":" second ]

hour            =       2DIGIT / obs-hour

minute          =       2DIGIT / obs-minute

second          =       2DIGIT / obs-second

zone            =       (( "+" / "-" ) 4DIGIT) / obs-zone
```

So something such as `12 Jun 14` is actually a valid date according to RFC2822, just not a valid date time. Note that years may be two digits as that is what `obs-year` is (obsolete year from RFC 822, which specifies last two digits of the century). 

Is elfeed capable of parsing RFC2822 *dates* (not date times)? What sort of format would work given that the *time* is not available?

**Comment by skeeto** [comment]
The "date" is just a component of date-time and isn't valid or
meaningful by itself, just as you couldn't use a "day-of-week" by
itself. The RSS 2.0 spec specifically says "date-time" (again, remember
that they listed the wrong RFC, because the examples are RFC2822):

> All date-times in RSS conform to the Date and Time Specification of
> RFC 822, with the exception that the year may be expressed with two
> characters or four characters (four preferred)."

Elfeed relies on Emacs' date-to-time function for parsing RFC2822. If
that parses your dates correctly, then it will work correctly in Elfeed.
If you don't have a meaningful time to use, pick midnight.

**Comment by gibiansky** [comment]
Sure thing.

**Comment by deepfire** [comment]
@gibiansky, that's what I found out:

Currently the feed has the dates are in the `Wed,  8 Apr 2015 :: ` format, which, when fed to
`date-to-time` function of Emacs, causes an error:

```
ELISP> (date-to-time "Wed,  8 Apr 2015 :: ")
*** Eval error ***  Invalid date: Wed,  8 Apr 2015 :: 
```

..whereas `Wed,  8 Apr 2015 00:00:00 ` seems to work:

```
ELISP> (date-to-time "Wed,  8 Apr 2015 00:00:00 ")
(21796 17744)
```

**Comment by gibiansky** [comment]
I know how to fix this, I am just still trying to get around to it...

**Comment by deepfire** [comment]
This was long since resolved by the RSS author, closing..
